### ISSUE TITLE
Director Add new Icinga UserGroup is no longer possible

### ISSUE THREAD

**Issue by u10t010** [Icinga/icingaweb2-module-director#2831] opened 2023-11-08 10:03 UTC
## Expected Behavior
in Icinga GUI in Director in Notifications add a UserGroup 

## Current Behavior
its no longer possible in Icinga GUI in Director in Notifications to add a UserGroup (maybe since upgrade to Director 1.11.0)
Error Message: Trying to get invalid property "assign_filter" (DbObject.php:271)

## Your Environment
* Director version (System - About):  Modul Version 1.11.0
* Icinga Web 2 version and modules (System - About): 2.12.0
* Icinga 2 version (`icinga2 --version`): r2.14.0-1
* Operating System and version: Debian 12 (bookworm)
* Webserver, PHP versions: 8.2.12

Could you be so kind and help us please?

**Comment by idandr** [comment] 2023-11-08 20:44
Looks like a duplicate of #2784.

**Comment by nilmerg** [comment] 2024-01-18 08:39
Duplicate of #2784

**Closed by nilmerg** 2024-01-18 08:39 UTC
