### ISSUE TITLE
Show at Hosts results in a blank page

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icingaweb2-module-director#1134] opened 2017-08-29 13:33 UTC
Show at Hosts results in a blank page:

![bildschirmfoto 2017-08-29 um 15 31 44](https://user-images.githubusercontent.com/3973350/29823579-5b16e55e-8ccf-11e7-898f-62042d1cbecc.png)

# Environment
Director version (System - About): master, Git commit: a9b562421275d250eb071547eac7ba062b70a848
Icinga Web 2 version and modules (System - About): 2.4.1
Icinga 2 version (icinga2 --version): r2.7.0-1
Operating System and version: CentOS Linux release 7.3.1611 (Core)
Webserver, PHP versions: PHP 5.4.16

**Comment by Thomas-Gelf** [comment] 2017-08-29 13:40
That's pretty strange, "show" should only point to the monitoring module. Anything related in your web servers error log? Do you see an error when closing the left part by clicking the X sign?

**Comment by mwaldmueller** [comment] 2017-08-29 13:43
No, there's nothing in the logs. But when I click on the X sign in the middle, the Host detail appears:
![bildschirmfoto 2017-08-29 um 15 42 06](https://user-images.githubusercontent.com/3973350/29824058-c0081a72-8cd0-11e7-80be-37134d988946.png)

**Comment by Thomas-Gelf** [comment] 2017-08-29 13:45
Could you please:
* reproduce the problem
* use your mouse to select as much of your screen as possible
* right click, "Show selection source"
* send me the shown HTML

Just going to "view source" would probably not help, as the browser might cheat you. Something weird seems to be going on here and messing with the HTML.

**Comment by Thomas-Gelf** [comment] 2017-08-29 13:46
Oh... I think I got it... sh***t :laughing:

**Comment by Thomas-Gelf** [comment] 2017-08-29 14:03
In your first screen-shot at the bottom left you can see "Host" - at least part of this. Guess this is the right-hand container, but it moved downwards. The reason for this is that Director switched to a 50/50 column view for every resolution, but the rest of Icinga Web 2 is 33/66 for wide screens. Now, what happens in your example is that Director claims 50% on the left hand and monitoring 66% on the right hand. You should buy a screen with 116% width :laughing:

So, i guess if you resize your browser to something lower than 1400px this issue should not appear.

Will have to find a fix for this.

**Closed** 2017-09-04 07:50 UTC
Labels: bug
