### ISSUE TITLE
Three Level scenario with Master, Satellites, and Clients configuration using Director

### ISSUE THREAD

**Issue by BlackDrag0n** [Icinga/icingaweb2-module-director#859] opened 2017-03-17 12:12 UTC
Hello,

I need a big help.

I'm trying to configurate a Three Level scenario with 1 Master, 1 Satellite, and 1 Client using Director over a month, and i'm already bleed from my brain xD

Can someone help me and please explain step-by-step what i need to do.

Please help me I'm desperated!!!!!!

**Comment by Thomas-Gelf** [comment] 2017-03-17 12:29
* connect your Satellite to your master
* run kickstart
* create a host for "Client name" with the Director, telling it that this should be an Agent being in the "Satellite Zone name" zone

The "Agent"-Tab will then provide you with everything you need to get it started, as shown in the [documentation](https://github.com/Icinga/icingaweb2-module-director/blob/master/doc/24-Working-with-agents.md). Screens look slightly different in latest versions, and Director now allows you to do at a host level what has formerly been restricted to templates - but the documentation should still fit.

Regards,
Thomas

NB, well-meant advice: I consider it impolite to yell "Please explain me everything I need to do" in an issue tracker without providing ANY details about what you did until know, or where you are facing problems. What do you expect people to answer? Should they ask you for every single detail step by step? Should someone write a dedicated manual for you? Then a training or asking some Icinga partner for consulting might be the better choice for you. You won't find many friends in OpenSource communities this way.

**Comment by BlackDrag0n** [comment] 2017-03-17 12:47
I'm sorry for my text.

- connect your Satellite to your master

When you refer to connect the satellite to the master you are talking about running the icinga2 node wizard on the satellite correct?

- run kickstart

I have read in forums that to run kickstart first i need to change the  File: /etc/icinga2/zones.conf, that's my file where i create the master zone and the satellite zone and add the director global zone thats correct?

File: /etc/icinga2/zones.conf

object Endpoint "icingamaster" {
  host = "192.168.0.14"
}
object Endpoint "satellite" {
  host = "192.168.0.19"
}
object Zone "icingamaster" {
  endpoints = [ "icingamaster" ]
}
object Zone "zona_1" {
  endpoints = [ "satellite" ]
  parent = "icingamaster"
}
/* sync global commands */
object Zone "director-global" {
  global = true
}

**Comment by Thomas-Gelf** [comment] 2017-03-17 12:53
Much better :-) And yes, that's how it should work. node wizard is a quick way to connect a satellite, you can also manually create the config (and it's certificates) if you want, the Icinga 2 documentation shows related examples. When changing infrastructure-related configuration on the master please restart Icinga and trigger the Director Kickstart again from the Infrastructure dashboard. That way it's easily possible to add additional satellites or zones later on.

Do not waste time with the Client config, create it in the Director - and it will provide you with all you need to get also the Client (Agent) connected and running.

You still didn't explain what exactly is going wrong for you. If you have connection problems please check your Icinga log files and eventually share related snippets in case something is not clear.

**Comment by BlackDrag0n** [comment] 2017-03-17 13:53
The problem is this:

First i configure in the icinga master the file /etc/icinga2/zones.conf with this configuration, adding the zone for director:

object Endpoint "icingamaster" {
host = "192.168.1.191"
}
object Endpoint "satellite" {
host = "192.168.1.180"
}
object Zone "icingamaster" {
endpoints = [ "icingamaster" ]
}
object Zone "zona_1" {
endpoints = [ "satellite" ]
parent = "icingamaster"
}
/* sync global commands */
object Zone "director-global" {
global = true
}

Second I connect the satellite to the master with icinga2 node wizard, this is the configuration that i do.

[Configuration Connectio Master Satellite.txt](https://github.com/Icinga/icingaweb2-module-director/files/850619/Configuration.Connectio.Master.Satellite.txt).

Then i run the kickstart on the director and it imported the zones and endpoints that i create on the file /etc/icinga2/zones.conf
Then i create a template for the generic host with the check command hostalive, after that i add in director the host, importing the template that i create.
And i run the icinga agent script given by icinga director on the client.

The problem is that the client check, keep stuck in pending status.

**Comment by Thomas-Gelf** [comment] 2017-03-17 13:59
The host check should in that case run on the Satellite if you didn't do anything special and just followed the given instructions. So, at this point the Agent is not involved yet, you can ignore it for now. Your satellite might not yet be connected to your master, that's where I would start my research. Please check the icinga2.log on both nodes for connection problems.

**Comment by BlackDrag0n** [comment] 2017-03-17 14:18
Should i do icinga2 node wizard on the master after i install director or before?

**Comment by Thomas-Gelf** [comment] 2017-03-17 15:13
Doesn't really matter. And that part already worked for you, didn't it? I do not want to ask you for a third time to check your logs for any hint. I have no idea whether you even looked at them, whether you found something, whether they told you that the satellite is connected or not.

I'm out, eventually someone else wants to jump in to help you.

**Comment by BlackDrag0n** [comment] 2017-03-17 16:14
This is the icinga2 log

[icinga2.txt](https://github.com/Icinga/icingaweb2-module-director/files/851148/icinga2.txt)

The api failed to connect, if you could take a look, i apreciated.

**Comment by SMUsamaShah** [comment] 2018-03-02 16:39
I want to do the same (1 master, 1 satellite, 1 client) using director. The problem is that Icinga can not be installed on clients, only nagios nrpe can be installed. I can successfully connect such client with master directly. But its not working when satellite comes in between.

1. Ran icinga wizard on the satellite system while providing it master ip and cn. 
2. Created two new zones Satellite and Client using director, default master zone already exists. Parent of Client zone is Satellite, parent of Satellite zone is master.  
3. Created two new endpoints, for each Satellite and Client as Cluster Zone and ip addresses of respective systems.
4. Added satellite system as a new host, with Cluster Zone set as Satellite, Icinga2 Agent, Establish connection and Accepts config are all set to Yes.
5. Added client system as a new host, set Cluster Zone to Client, Icinga2 Agent to No.

This client has NRPE service running but no service checks could be executed.

**Comment by Thomas-Gelf** [comment] 2019-10-14 14:16
This issue is very old, and the last comment not related at all. Closing this for now, please feel free to open a new issue when still facing problems.

**Closed by Thomas-Gelf** 2019-10-14 14:16 UTC
