### ISSUE TITLE
"Undefined offset" error in getParentById() function when rendering configuration

### ISSUE THREAD

**Issue by terra-nova** [Icinga/icingaweb2-module-director#1550] opened 2018-06-27 13:57 UTC
## Expected Behavior
Rendering the configuration (Director -> Deployments -> Render Config) should complete successfully or produce a meaningful error message.

## Current Behavior
Rendering configuration fails with the following message:  `Undefined offset: 174 (TemplateTree.php:192)`

## Possible Solution

The error indicates an invalid key for accessing the associative array TemplateTree->names in the TemplateTree::getParentsById() function.

```
180     public function getParentsById($id)
181     {
182         $this->requireTree();
183
184         if (array_key_exists($id, $this->parents)) {
185             return $this->parents[$id];
186         }
187
188         $this->requireObjectMaps();
189         if (array_key_exists($id, $this->objectMaps)) {
190             $parents = [];
191             foreach ($this->objectMaps[$id] as $pid) {
192                 $parents[$pid] = $this->names[$pid];
193             }
194
195             return $parents;
196         } else {
197             return [];
198         }
199     }
```

Now I have no idea exactly how we managed to get ourselves into this situation, but I think there was some unintended deletion of templates followed by restoration attempts using the Director's Activity Log,  followed by further manual changes in the Director UI (sigh).

Anyway, the function breaks with $pid = 174 because the "names" associative array does not have that key. I naively worked around the error by altering the PHP file TemplateTree.php as follows:

```
...
192                 if (array_key_exists($pid, $this->names)) {
193                     $parents[$pid] = $this->names[$pid];
194                 }
...
```

This helped in so far as we can once again genereate configuration from Icinga, but I have no idea if this change might have any unintended side effects.

## Steps to Reproduce (for bugs)

Hard to say.. I suspect some unfortunate misconfiguration by some of our less experienced Icinga users. I would investigate further but I have no clue on how to log variable values from the PHP code. Output of `error_log()` does not seem to be captured in any of our Icingaweb/Apache log files.

## Your Environment

* Director version (System - About): Git head from today (https://github.com/Icinga/icingaweb2-module-director/commit/35815e0dad9bf7370a68f5128d17506b9a9530cb)
* Icinga Web 2 version and modules (System - About): 2.5.3
* Icinga 2 version (`icinga2 --version`): 2.8.4
* Operating System and version: CentOS 7.5 x64
* Webserver, PHP versions: Apache 2.4, PHP 7.1 from SCL

**Comment by lazyfrosch** [comment] 2018-07-09 12:31
This is most likely a duplicate of #1115

Please see my comment: https://github.com/Icinga/icingaweb2-module-director/issues/1115#issuecomment-402648585

**Closed by lazyfrosch** 2018-07-09 12:31 UTC
Labels: duplicate
