### ISSUE TITLE
Director 1.10.1 cannot create database schema

### ISSUE THREAD

**Issue by redbob365** [Icinga/icingaweb2-module-director#2625] opened 2022-09-27 19:55 UTC
## Describe the bug

Hi,

I'm trying to install director module in Icinga2 Web, but I cannot create database schema.
I have tried several times, but not successfully at all;

## To Reproduce
````
1. drop database director;
2. CREATE DATABASE director CHARACTER SET 'utf8';
3. GRANT ALL ON director.* TO director@localhost;
4. Application / Resources / Create a New Resource: Director DB (Successfully validated) - Saved;
````
when I go to `Icinga Director Setup: Create Schema` and click on `Create Schema` button, this error ocurrs:
````
 Migration 0 failed (SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'imports') while running CREATE TABLE branched_icinga_service_set ( uuid VARBINARY(16) NOT NULL, branch_uuid VARBINARY(16) NOT NULL, branch_created ENUM('y', 'n') NOT NULL DEFAULT 'n', branch_deleted ENUM('y', 'n') NOT NULL DEFAULT 'n', object_name VARCHAR(128) DEFAULT NULL, object_type ENUM('object', 'template', 'external_object') DEFAULT NULL, host VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, assign_filter TEXT DEFAULT NULL, imports TEXT DEFAULT NULL, imports TEXT DEFAULT NULL, set_null TEXT DEFAULT NULL, PRIMARY KEY (branch_uuid, uuid), INDEX search_object_name (object_name), CONSTRAINT icinga_service_set_branch FOREIGN KEY branch (branch_uuid) REFERENCES director_branch (uuid) ON DELETE CASCADE ON UPDATE CASCADE ) ENGINE=InnoDB DEFAULT CHARSET=utf8
````
What I cannot undestand is why these duplicated columns, because before the Creating Schema command, I go to mysql > `use director; > show tables;` the output is `Empty set (0.00 sec); `

## Your Environment

* Version used (`icinga2 --version`): **r2.13.5-1**
* Operating System and version: **Ubuntu 20.04.5 LTS**
* Enabled features (`icinga2 feature list`):  `api checker ido-mysql mainlog notification`
* Icinga Web 2 version and modules (System - About): `2.11.1 - php 8.1.10 - director 1.10.0 - incubator 0.18.0 - monitoring 2.11.1;`
* Config validation (`icinga2 daemon -C`):
````
[2022-09-27 20:09:36 +0000] information/cli: Icinga application loader (version: r2.13.5-1)
[2022-09-27 20:09:36 +0000] information/cli: Loading configuration file(s).
[2022-09-27 20:09:36 +0000] information/ConfigItem: Committing config item(s).
[2022-09-27 20:09:36 +0000] information/ApiListener: My API identity: srvicinga2-mt
[2022-09-27 20:09:36 +0000] information/ConfigItem: Instantiated 2 HostGroups.
[2022-09-27 20:09:36 +0000] information/ConfigItem: Instantiated 1 IcingaApplication.
[2022-09-27 20:09:36 +0000] information/ConfigItem: Instantiated 1 Host.
[2022-09-27 20:09:36 +0000] information/ConfigItem: Instantiated 1 FileLogger.
[2022-09-27 20:09:36 +0000] information/ConfigItem: Instantiated 1 Downtime.
[2022-09-27 20:09:36 +0000] information/ConfigItem: Instantiated 1 IdoMysqlConnection.
[2022-09-27 20:09:36 +0000] information/ConfigItem: Instantiated 1 CheckerComponent.
[2022-09-27 20:09:36 +0000] information/ConfigItem: Instantiated 13 Notifications.
[2022-09-27 20:09:36 +0000] information/ConfigItem: Instantiated 3 Zones.
[2022-09-27 20:09:36 +0000] information/ConfigItem: Instantiated 1 Endpoint.
[2022-09-27 20:09:36 +0000] information/ConfigItem: Instantiated 2 ApiUsers.
[2022-09-27 20:09:36 +0000] information/ConfigItem: Instantiated 1 ApiListener.
[2022-09-27 20:09:36 +0000] information/ConfigItem: Instantiated 1 NotificationComponent.
[2022-09-27 20:09:36 +0000] information/ConfigItem: Instantiated 244 CheckCommands.
[2022-09-27 20:09:36 +0000] information/ConfigItem: Instantiated 1 UserGroup.
[2022-09-27 20:09:36 +0000] information/ConfigItem: Instantiated 3 ServiceGroups.
[2022-09-27 20:09:36 +0000] information/ConfigItem: Instantiated 3 TimePeriods.
[2022-09-27 20:09:36 +0000] information/ConfigItem: Instantiated 1 User.
[2022-09-27 20:09:36 +0000] information/ConfigItem: Instantiated 1 ScheduledDowntime.
[2022-09-27 20:09:36 +0000] information/ConfigItem: Instantiated 12 Services.
[2022-09-27 20:09:36 +0000] information/ConfigItem: Instantiated 2 NotificationCommands.
[2022-09-27 20:09:36 +0000] information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
[2022-09-27 20:09:36 +0000] information/cli: Finished validating the configuration file(s).

````

**Comment by lippserd** [comment] 2022-10-04 07:44
Hi,

This is a duplicate of #2609.

All the best,
Eric

**Closed by lippserd** 2022-10-04 07:44 UTC

**Comment by Thomas-Gelf** [comment] 2022-10-04 07:45
Thank you @lippserd! Just remove that duplicate line from mysql.sql, and it will work. v1.10.1 with this fix will be released within this week

**Comment by redbob365** [comment] 2022-10-04 20:35
> Thank you @lippserd! Just remove that duplicate line from mysql.sql, and it will work. v1.10.1 with this fix will be released within this week

Ok, @Thomas-Gelf. Could you send a warning when this fix willl arrive? Because I'm using `Director v.1.9.1` I receive this warning:
````
Your DB schema (migration #180) is newer than your code base. Downgrading Icinga Director is not supported and might lead to unexpected problems.
````

**Comment by Thomas-Gelf** [comment] 2022-10-04 20:37
@redbob365: no need to downgrade, existing installations are not affected by this issue

**Comment by redbob365** [comment] 2022-10-04 20:39
> @redbob365: no need to downgrade, existing installations are not affected by this issue

Yep, I understood. But I wanna upgrade Director to `1.10.1` when this fix will be released. Thanks

**Comment by C0rn3j** [comment] 2022-10-31 15:42
1.10.1 still has an issue with this that .2 fixes, see https://github.com/Icinga/icingaweb2-module-director/issues/2630
