### ISSUE TITLE
deploying a serviceset will fail

### ISSUE THREAD

**Issue by vita2** [Icinga/icingaweb2-module-director#1788] opened 2019-02-18 10:52 UTC
## Current Behavior
hello,

with latest Icinga Director i cannot deploy servicesets anymore. it fails with the following error:

```
[2019-02-18 11:06:16 +0100] information/cli: Icinga application loader (version: r2.10.2-1)
[2019-02-18 11:06:16 +0100] information/cli: Loading configuration file(s).
[2019-02-18 11:06:17 +0100] critical/config: Error: 'apply' is missing 'assign'/'for'
Location: in [stage]/zones.d/siteA/servicesets.conf: 121:1-121:13
[stage]/zones.d/siteA/servicesets.conf(119): /** Service Set 'mysql' **/
[stage]/zones.d/siteA/servicesets.conf(120): 
[stage]/zones.d/siteA/servicesets.conf(121): apply Service "mysql-bufferpool-hitrate" {
                                           ^^^^^^^^^^^^^
[stage]/zones.d/siteA/servicesets.conf(122):     host_name = "db01.domain.tld"
[stage]/zones.d/siteA/servicesets.conf(123):     import "mysql-health"
```

previously the director renders such kind of objects as `object Service "mysql-bufferpool-hitrate"`.

## Your Environment
* Director version (System - About): 89d4af564e98fa04600a4d9c6d565e903350435b
* Icinga Web 2 version and modules (System - About): 2.6.2
* Icinga 2 version (`icinga2 --version`): r2.10.2-1
* Operating System and version: Debian Jessie 9.8 (4.9.0-8-amd64)
* Webserver, PHP versions: Apache2 2.4.25-3+deb9u4 + PHP7 7.0.33-0+deb9u1

**Comment by Thomas-Gelf** [comment] 2019-02-18 12:24
That's.... strange. Could you please show the output of some queries? Let's start with this one:
```sql
SELECT id, object_type, assign_filter, host_id, service_set_id
  FROM icinga_service
 WHERE object_name = 'mysql-bufferpool-hitrate';
```

Thanks,
Thomas

**Comment by vita2** [comment] 2019-02-18 13:34
thanks for your response @Thomas-Gelf. sure, i will show you the output of the given query:

id | object_type | assign_filter | host_id | service_set_id
-- | -- | -- | -- | --
216 | apply | NULL | NULL | 3

**Comment by Thomas-Gelf** [comment] 2019-02-18 13:42
This might look weird, but could be correct. Object-Type `apply` (the filter should be on the set, so that's fine(), no `host_id` - but it renders `host_name = ...`. How has this Set been created? Manually? Are you able to reproduce this with a newly created Set?

Anyways, don't worry - this is only part of the picture. Next queries:

```sql
SELECT * FROM icinga_service_inheritance WHERE service_id = 216 OR parent_service_id = 216;
```

```sql
SELECT
    id, object_name, object_type, host_id, service_set_id
  FROM icinga_service
 WHERE id IN (
    SELECT service_id
      FROM icinga_service_inheritance
     WHERE parent_service_id = 19
 );
```

**Comment by vita2** [comment] 2019-02-18 14:38
i have created this service set manually in the webui without an apply rule. the assignment to a host is also done manually.

```sql
SELECT * FROM icinga_service_inheritance WHERE service_id = 216 OR parent_service_id = 216;
```

service_id | parent_service_id | weight
-- | -- | --
216 | 171 | 1

```sql
SELECT
    id, object_name, object_type, host_id, service_set_id
  FROM icinga_service
 WHERE id IN (
    SELECT service_id
      FROM icinga_service_inheritance
     WHERE parent_service_id = 171
 );
```

id | object_name | object_type | host_id | service_set_id
-- | -- | -- | -- | --
216 | mysql-bufferpool-hitrate | apply | NULL | 3
217 | mysql-bufferpool-wait-free | apply | NULL | 3
218 | mysql-clients-aborted | apply | NULL | 3
219 | mysql-connection-time | apply | NULL | 3
220 | mysql-connects-aborted | apply | NULL | 3
221 | mysql-keycache-hitrate | apply | NULL | 3
222 | mysql-log-waits | apply | NULL | 3
223 | mysql-long-running-procs | apply | NULL | 3
224 | mysql-qcache-hitrate | apply | NULL | 3
225 | mysql-qcache-lowmem-prunes | apply | NULL | 3
226 | mysql-slow-queries | apply | NULL | 3
227 | mysql-table-fragmentation | apply | NULL | 3
228 | mysql-tablecache-hitrate | apply | NULL | 3
229 | mysql-threadcache-hitrate | apply | NULL | 3
230 | mysql-threads-cached | apply | NULL | 3
231 | mysql-threads-connected | apply | NULL | 3
232 | mysql-threads-created | apply | NULL | 3
233 | mysql-threads-running | apply | NULL | 3
234 | mysql-uptime | apply | NULL | 3
249 | mysql-index-usage | apply | NULL | 3
250 | mysql-myisam-keycache-hitrate | apply | NULL | 3
251 | mysql-innodb-bufferpool-hitrate | apply | NULL | 3
585 | mysql-dbsize-XYZ001 | object | 73 | NULL
586 | mysql-dbsize-XYZ002 | object | 73 | NULL
587 | mysql-dbsize-XYZ003 | object | 73 | NULL
588 | mysql-dbsize-XYZ004 | object | 73 | NULL
589 | mysql-dbsize-XYZ005 | object | 73 | NULL
590 | mysql-dbsize-XYZ006 | object | 73 | NULL
591 | mysql-dbsize-XYZ007 | object | 73 | NULL
592 | mysql-dbsize-XYZ008 | object | 75 | NULL
593 | mysql-dbsize-XYZ009 | object | 75 | NULL
594 | mysql-dbsize-XYZ010 | object | 75 | NULL
595 | mysql-dbsize-XYZ011 | object | 75 | NULL
596 | mysql-dbsize-XYZ012 | object | 75 | NULL

> Are you able to reproduce this with a newly created Set?

no, i cannot reproduce it with a newly created set. the config preview shows the correct object type:
```
zones.d/siteA/servicesets.conf
/** Service Set 'mysql-test' **/

object Service "mysql-bufferpool-hitrate" {
    host_name = "db01.domain.tld"
    import "mysql-health"

    vars.mysql_health_mode = "bufferpool-hitrate"
}
```

```sql
SELECT id, object_type, assign_filter, host_id, service_set_id
  FROM icinga_service
 WHERE object_name = 'mysql-bufferpool-hitrate'
```

id | object_type | assign_filter | host_id | service_set_id
-- | -- | -- | -- | --
216 | apply | NULL | NULL | 3
952 | object | NULL | NULL | 76

**Comment by terra-nova** [comment] 2019-02-19 09:55
We have the same issue here since updating to the v1.6.1 branch. Db is PostgreSQL, though.

**Comment by gasmick** [comment] 2019-02-19 14:24
Same here with 1.6.1 and MySQL

**Comment by terra-nova** [comment] 2019-02-20 11:53
Director renders invalid Icinga2 configuration files for us with service sets that have been manually to individual host objects (e.g. not via templates).

E.g. it tries to create an apply rule, but without any assign/ignore statements, which is then rejected by Icinga2.

```
apply Service "CPU" {
    host_name = "xyz"
    import "VMware VM: CPU Utilization"

    vars....

    import DirectorOverrideTemplate
}
```

Relevant code for generating the invalid configuration is in library/Director/Object/IcingaServiceSet.php, function `renderToConfig()`.

```
289         foreach ($services as $service) {
290             if ($filter = $this->get('assign_filter')) {
291                 $service->set('object_type', 'apply');
292                 $service->set('assign_filter', $filter);
293             } elseif ($hostId = $this->get('host_id')) {
294                 $host = $this->getRelatedObject('host', $hostId)->getObjectName();
295                 if (in_array($host, $this->getBlacklistedHostnames($service))) {
296                     continue;
297                 }
298                 $service->set('host_id', $this->get('host_id'));
299             } else {
300                 // Service set template without assign filter or host
301                 continue;
302             }
```

I hacked around the issue by inserting the following code before line 299:

```
299                 if ($service->get('object_type') == 'apply' && ! ($service->hasBeenAssignedToHostTemplate())) {
300                     $service->set('object_type', 'object');
301                 }
```

For this to work I had to alter the function declaration `hasBeenAssignedToHostTemplate()` in `library/Director/Objects/IcingaService.php`, line 462, from `protected` to `public`.

Whether or not this is a good idea... I don't know.

But we now can deploy our configuration again, which we could not after having installed Director 1.6.1, even after having revertied to 1.6.0 again.

**Comment by syrof** [comment] 2019-02-21 10:15
Same for me.
Service-set manually assigned.
Director 1.6.1 deployment failed.
Revert to 1.6.0 deployment succesed.

`[2019-02-21 10:50:31 +0100] information/cli: Icinga application loader (version: r2.10.2-1)
[2019-02-21 10:50:31 +0100] information/cli: Loading configuration file(s).
[2019-02-21 10:50:31 +0100] critical/config: Error: 'apply' is missing 'assign'/'for'
Location: in [stage]/zones.d/../servicesets.conf: 151:1-151:13
[stage]/zones.d/../servicesets.conf(149): /** Service Set 'http-ext' **/
[stage]/zones.d/../servicesets.conf(150): 
[stage]/zones.d/../servicesets.conf(151): apply Service "http" {
                                                          ^^^^^^^^^^^^^
[stage]/zones.d/../servicesets.conf(152):     host_name = ".."
[stage]/zones.d/../servicesets.conf(153):     import "http"`

**Comment by Thomas-Gelf** [comment] 2019-02-21 10:17
Will have a look this evening, for now please stay with 1.6.0 if affected by this issue.

**Comment by Thomas-Gelf** [comment] 2019-02-26 12:54
Sorry for the delay, please follow #1789 - will be fixed immediately.

**Closed by Thomas-Gelf** 2019-02-26 12:54 UTC
Labels: bug, duplicate

**Comment by Thomas-Gelf** [comment] 2019-02-26 12:55
NB: A fix has been pushed to the support/1.6 branch, please let me know whether it works for you - I'll then schedule v1.6.2

**Comment by terra-nova** [comment] 2019-02-26 13:56
Fixes the problems for us. Thanks.

**Comment by Thomas-Gelf** [comment] 2019-02-26 14:04
Glad to hear that, fix has been picked into the master branch.

**Comment by vita2** [comment] 2019-02-26 15:14
fixes the issues for me, too. thank you @Thomas-Gelf 👍

**Comment by Thomas-Gelf** [comment] 2019-02-26 15:17
Thanks for reporting it @vita2! I scheduled v1.6.2 for tomorrow.
