### ISSUE TITLE
Basket: add hosts/services/service apply to basket

### ISSUE THREAD

**Issue by friesoft** [Icinga/icingaweb2-module-director#1811] opened 2019-03-26 21:32 UTC
## Expected Behavior
We would like to export/import host objects from one director instance to another. Host templates and groups can be exported, so why not also hosts? Bug? Just not done yet?

## Current Behavior
Virtually every other icinga object can be exported, but not hosts.

## Possible Solution
Implement host export/import

## Steps to Reproduce (for bugs)
Create a new basket, tick all the boxes and create a snapshot - there are no hosts in the basket

## Your Environment
* Director version (System - About): master (0d3649ce3f2a79928d6007caec47c4be5bf54e5e)
* Icinga Web 2 version and modules (System - About): 2.6.2
* Icinga 2 version (`icinga2 --version`): v2.10.2-257-g856d3a1
* Operating System and version: Red Hat 7
* Webserver, PHP versions: Apache 2.4, PHP 7

**Comment by Thomas-Gelf** [comment] 2019-03-26 22:24
> We would like to export/import host objects from one director instance to another. Host templates and groups can be exported, so why not also hosts? Bug? Just not done yet?

As the introduction on the `director/baskets` page states, this is intentional. Main reason are mostly different workflows and different amounts of data. Most environments I personally work with have thousands of hosts, and most of them are created automatically. There are automated changes every few minutes. It's pointless to export them to another Director instance. You export related Import and Sync definitions and are ready to go.

Technically it would be easy to allow people to use the basket for single host objects. But this would obviously lead people to use it as a snapshot mechanism, and that wouldn't perform well in largish environments.

> Virtually every other icinga object can be exported, but not hosts.

Apart from REST API and CLI, what's wrong with the "Download as JSON" option provided on your hosts list? It's a single click, it ships all hosts with all properties. And it streams very fast, even with a huge amount of hosts.

> Implement host export/import

While technically possible I understand that one doesn't want to manually define a JSON Import with a related Sync Rule definition for hosts exported in a well-known JSON format by the Director itself. I could imagine offering a simple upload possibility for exported Hosts, with just two simple options:

* In case a Host exists: ignore / merge / replace
* Purge Hosts missing in the uploaded file: yes / no

Would that be helpful for you?

**Comment by friesoft** [comment] 2019-03-27 19:11
Looks like I overread the directory/baskets page. Sorry!
Thanks for the detailed explanation! 🙂

We have the task to do a one time export/import of an existing director instance and merge it with another existing one. We are basically talking about around 50 handcrafted hosts.

From a users standpoint I guess it would be more straightforward if every object could be exported/imported using the baskets, but of course I understand your concerns.

i guess your proposed solution would work fine for us :)

**Comment by friesoft** [comment] 2019-04-12 15:50
Hm.. so this restriction with configuration baskets also applies to services and service apply rules. Any ideas for those?
Using the "Downloas as JSON" I can at least import the hosts/services using some scripting (icingacli create host --json for each entry in the objects array).
But this doesn't work for service apply rules as they can't be downloaded as JSON :(

**Comment by friesoft** [comment] 2019-04-16 21:31
@Thomas-Gelf maybe you could take a look at the pullrequest if it is going into the right direction.
For importing I still resort to icingacli..

**Comment by stevie-sy** [comment] 2019-05-20 08:33
We have also this Problem: 
We are also using the basket and it's a really cool feature from the director for backup und export the data from a production in a test Environment.  So every time we want to Transfer the data from one System to the other we have to re-create (new) apply rules manually. So it would be nice if the export from apply-rules would also be implemented.

**Comment by Thomas-Gelf** [comment] 2019-09-19 22:08
The linked Pull-Request has been merged.
Work-around for Service Apply Rules: use Applied Service Sets.

Please expect Service Apply Rules to be implemented, but definitively not for v1.7.x. We're facing the problem that Service Apply Rule names are not unique in Icinga 2 by design. This has been overlooked in the very first Director schema versions, and now it causes problems with Baskets and other features. This will be addressed, but it is... complicated. We'll probably opt for a UUID-based strategy, but implementing this in a non-breaking way is going to be tricky.

Closing this issue for now, please feel free to open new/dedicated ones if you have dedicated questions for specific object types.

**Closed by Thomas-Gelf** 2019-09-19 22:08 UTC
Labels: enhancement, feedback

**Comment by budulinek** [comment] 2020-08-31 22:13
Sorry for commenting on closed issue. But I am struggling to implement a reliable backup strategy of a very small environment. Just a handful of hosts configured via Icinga Director. What I tried:

- Icinga conf files (from /var/lib/icinga2/api). Easy to backup, but impossible to restore (Director renders conf files but can not import them).
- mysql dump. Easy to backup and restore, but this is a very crude solution. You can not configure which items to backup and which items to restore.
- Baskets. Seems like an ideal solution (and baskets are officially advertised as a backup solition). Easy to backup, easy to restore. Easily configurable, you can choose which items to backup, which items to restore. BUT.... It is very frustrating that you can not add hosts/services/service apply to baskets.

> Most environments I personally work with have thousands of hosts, and most of them are created automatically. There are automated changes every few minutes. It's pointless to export them to another Director instance. You export related Import and Sync definitions and are ready to go.
> 
> Technically it would be easy to allow people to use the basket for single host objects. But this would obviously lead people to use it as a snapshot mechanism, and that wouldn't perform well in largish environments.

But what about "smallish" environments? People with manually edited services and hosts (via Director) are left with crude database dump as the only solution. Please consider adding hosts/services/service apply to basket. Those (like you) with large environments with automatically created hosts can easily exclude hosts from basket snapshots.
