### ISSUE TITLE
Feature Request: Override service vars of specific services created by an apply rule

### ISSUE THREAD

**Issue by matthenning** [Icinga/icingaweb2-module-director#1341] opened 2017-12-20 11:56 UTC
We have a scenario where we dynamically create a list (custom var on a host template) and use apply rules to apply a number of services to this host template using the list.

Currently you cannot override custom vars on a specific service created by this apply rule.

Consider an array on a host template:
```
vars.adapters = [
  'adapter01', 
  'adapter02'
]
```

And an apply rule utilizing this array applied to the host template:
```
apply Service "Adapter Status " for (config in host.vars.adapters) {
    import "Adapter Service"

    assign where host.vars.adapters

    import DirectorOverrideTemplate
}
```

You can now see the apply rule under the host template's services, but not one service for every key in the vars.adapters array (Adapter Status adapter01, Adapter Status adapter02).
Overriding vars there results in a config similar to this:

```
vars["_override_servicevars"] += {
    "Adapter Status " = {
        crit = "offline"
    }
}
```

What I would expect would be a list of resulting services and the option to override vars on each one, like this:

```
vars["_override_servicevars"] += {
    "Adapter Status adapter01" = {
        crit = "offline"
    }
}
```

**Comment by friesoft** [comment] 2017-12-20 12:00
Duplicate of #831

**Closed** 2018-06-08 21:36 UTC
Labels: duplicate
