### ISSUE TITLE
Modify link in service throws exception when there is icingadb only

### ISSUE THREAD

**Issue by krappi01** [Icinga/icingaweb2-module-director#2563] opened 2022-07-13 16:27 UTC
## Expected Behavior
The modify link in a service should work

## Current Behavior
When I click on modify in any service from icingadb-web detail view I get the following exception:

> Uncaught Error: Call to a member function select() on null in /usr/share/icingaweb2/modules/director/library/Director/Monitoring.php:141
Stack trace:
#0 /usr/share/icingaweb2/modules/director/library/Director/Monitoring.php(41): Icinga\Module\Director\Monitoring->prepareServiceKeyColumnQuery()
#1 /usr/share/icingaweb2/modules/director/library/Director/Monitoring.php(78): Icinga\Module\Director\Monitoring->hasService()
#2 /usr/share/icingaweb2/modules/director/application/controllers/HostController.php(37): Icinga\Module\Director\Monitoring->authCanEditService()
#3 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ActionController.php(57): Icinga\Module\Director\Controllers\HostController->checkDirectorPermissions()
#4 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(64): Icinga\Module\Director\Web\Controller\ActionController->init()
#5 /usr/share/php/Icinga/Web/Controller/ActionController.php(170): Icinga\Module\Director\Web\Controller\ObjectController->init()
#6 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(59): Icinga\Web\Controller\ActionController->__construct()
#7 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch()
#8 /usr/share/php/Icinga/Application/Web.php(290): Zend_Controller_Front->dispatch()
#9 /usr/share/php/Icinga/Application/webrouter.php(105): Icinga\Application\Web->dispatch()
#10 /usr/share/icingaweb2/public/index.php(4): require_once('...')
#11 {main}
thrown

I think it started after I disabled the old monitoring module and activated [icingadb-web](https://github.com/Icinga/icingadb-web) and disabled the old ido-database / removed the ido ressource

## Your Environment

Icinga Web 2 version and modules (System - About): 2.11.1

Loaded Libraries:
icinga/icinga-php-thirdparty 0.11.0
icinga/icinga-php-library 0.9.1

Loaded Modules:
director 1.9.1
doc 2.11.1
graphite 1.2.1
icingaclassictheme 0.5.1
icingadb 1.0.0
incubator 0.17.0
migrate 2.11.1
pdfexport 0.10.2
reactbundle 0.9.0
vspheredb 1.4.0

Web browser used: Firefox 101.0.1
Icinga 2 version used (icinga2 --version): r2.13.4-1
PHP version used (php --version): 8.1.8
Server operating system and version: CentOS Stream release 8

**Comment by log1-c** [comment] 2022-08-05 06:08
Can confirm.
Demo-Setup is IcingaDB and IcingaDB-Web only and the modify link throws this exact error.

**Comment by minatoyama** [comment] 2022-10-03 09:42
In the meantime, is there a work-around for this bug?

**Comment by krappi01** [comment] 2022-10-04 09:07
> In the meantime, is there a work-around for this bug?

Yes I did in /usr/share/icingaweb2/modules/director/library/Director/Monitoring.php line 41:

`return true;`

**Comment by EmTeedee** [comment] 2022-10-12 15:07
duplicate of #2533

**Comment by mwaldmueller** [comment] 2022-11-22 05:38
Any news on this?

**Closed** 2022-12-29 15:31 UTC
Labels: ref/IP

**Comment by Thomas-Gelf** [comment] 2023-02-23 10:56
> Thanks! That works for hosts and direct-applied services, not for apply rules or service sets. But at least it's something :)

This fix has been reverted and replaced with a [huge commit](https://github.com/Icinga/icingaweb2-module-director/commit/4025471) for #2712. Could you please test whether the current master branch fixes your issue?

Thanks,
Thomas

**Comment by mwaldmueller** [comment] 2023-05-31 09:37
The current master ac73affcb481689102f47823e1b6affde621b52e fixes the issue.

**Comment by log1-c** [comment] 2023-07-05 13:02
Could this please be released in a v1.10.3, if v1.11.0 is still further away from release?
This is a little show-stopper in the migration from IDO to IcingaDB
