### ISSUE TITLE
Getting the deployment-status/progress via REST API

### ISSUE THREAD

**Issue by thille-IM** [Icinga/icingaweb2-module-director#959] opened 2017-06-06 13:17 UTC
In a larger setup I run into the problem, where the deployment takes a considerable time. But my script needs the director to have finished deployment before it can proceed.

Therefore it would be very helpfull if the status of the (current) deployment could be read via REST API.

**Comment by Thomas-Gelf** [comment] 2017-06-22 06:35
Makes sense.

**Comment by rattacresh** [comment] 2017-07-10 19:27
It would also be great to be able to obtain information from the REST API whether the last deployment failed and what the error messages were.

**Comment by tobiasvdk** [comment] 2017-07-26 19:56
Looks like a duplicate of #679.

**Comment by mkayontour** [comment] 2018-01-09 11:02
Having the same issue, I want to check if my deployment was successfull over the rest api.

**Comment by Thomas-Gelf** [comment] 2020-11-28 16:16
Has been implemented with #2187

**Closed by Thomas-Gelf** 2020-11-28 16:16 UTC
Labels: duplicate, enhancement
