### ISSUE TITLE
Editing inherited services (overrides) in host is broken

### ISSUE THREAD

**Issue by knerhood** [Icinga/icingaweb2-module-director#723] opened 2017-01-17 18:22 UTC
It appears that commit 9b6eda4e97950051ec1d77e429d42f171d07c853 breaks editing of inherited services. 

When trying to place an override on a specific service attached to host,  I get the following error when that commit is applied.

There is no such import: "juniper-ex"

```
#0 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaTemplateResolver.php(317): Icinga\Module\Director\Objects\IcingaTemplateResolver->getIdForName('juniper-ex')
#1 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaTemplateResolver.php(111): Icinga\Module\Director\Objects\IcingaTemplateResolver->getIdsForNames(Array)
#2 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaTemplateResolver.php(96): Icinga\Module\Director\Objects\IcingaTemplateResolver->listUnstoredParentIds()
#3 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaTemplateResolver.php(205): Icinga\Module\Director\Objects\IcingaTemplateResolver->listParentIds(NULL)
#4 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaTemplateResolver.php(226): Icinga\Module\Director\Objects\IcingaTemplateResolver->listFullInheritancePathIds(NULL)
#5 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/IcingaObjectFieldLoader.php(434): Icinga\Module\Director\Objects\IcingaTemplateResolver->listInheritancePathIds()
#6 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/IcingaObjectFieldLoader.php(501): Icinga\Module\Director\Web\Form\IcingaObjectFieldLoader->fetchFieldDetailsForObject(Object(Icinga\Module\Director\Objects\IcingaService))
#7 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/IcingaObjectFieldLoader.php(399): Icinga\Module\Director\Web\Form\IcingaObjectFieldLoader->loadDataFieldsForObject(Object(Icinga\Module\Director\Objects\IcingaService))
#8 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/IcingaObjectFieldLoader.php(361): Icinga\Module\Director\Web\Form\IcingaObjectFieldLoader->loadResolvedFieldsForObject(Object(Icinga\Module\Director\Objects\IcingaService))
#9 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/IcingaObjectFieldLoader.php(150): Icinga\Module\Director\Web\Form\IcingaObjectFieldLoader->prepareObjectFields(Object(Icinga\Module\Director\Objects\IcingaService))
#10 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/IcingaObjectFieldLoader.php(318): Icinga\Module\Director\Web\Form\IcingaObjectFieldLoader->getFields()
#11 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/IcingaObjectFieldLoader.php(166): Icinga\Module\Director\Web\Form\IcingaObjectFieldLoader->createElements(Object(Icinga\Module\Director\Forms\IcingaServiceForm))
#12 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/IcingaObjectFieldLoader.php(183): Icinga\Module\Director\Web\Form\IcingaObjectFieldLoader->getElements(Object(Icinga\Module\Director\Forms\IcingaServiceForm))
#13 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/DirectorObjectForm.php(318): Icinga\Module\Director\Web\Form\IcingaObjectFieldLoader->prepareElements(Object(Icinga\Module\Director\Forms\IcingaServiceForm))
#14 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/DirectorObjectForm.php(630): Icinga\Module\Director\Web\Form\DirectorObjectForm->prepareFields(Object(Icinga\Module\Director\Objects\IcingaService))
#15 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(451): Icinga\Module\Director\Web\Form\DirectorObjectForm->onRequest()
#16 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(463): Icinga\Module\Director\Web\Form\QuickForm->setRequest(Object(Icinga\Web\Request))
#17 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(322): Icinga\Module\Director\Web\Form\QuickForm->getRequest()
#18 /usr/share/icingaweb2/modules/director/application/controllers/HostController.php(277): Icinga\Module\Director\Web\Form\QuickForm->handleRequest()
#19 /usr/share/icingaweb2/modules/director/application/controllers/HostController.php(222): Icinga\Module\Director\Controllers\HostController->commonForServices()
#20 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Controllers\HostController->inheritedserviceAction()
#21 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('inheritedservic...')
#22 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#23 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#24 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#25 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#26 {main}
```

**Comment by friesoft** [comment] 2017-01-18 07:54
Duplicate of #722?

**Comment by lazyfrosch** [comment] 2017-01-18 08:00
yes seems like so, please refer to #722

**Closed by lazyfrosch** 2017-01-18 08:00 UTC
