### ISSUE TITLE
Error when trying to create an user group

### ISSUE THREAD

**Issue by RafaelSche** [Icinga/icingaweb2-module-director#2844] opened 2023-12-18 15:30 UTC
## Expected Behavior
I am trying to create an user group. Both through the GUI and the Director API results in the message below:

## Current Behavior
![Screenshot_2023-12-18_16-20-07](https://github.com/Icinga/icingaweb2-module-director/assets/47508551/71b196f8-59dd-40e3-bc08-550892fc778d)

## Possible Solution
I don't know

## Your Environment
* Icinga Web 2  2.12.1    
Git Commit    cd2daeb2cb8537c633d343a29eb76c54cd2ebbf2 
PHP Version   7.4.33    
MODULE             VERSION   
director           1.11.0    
icingadb           1.1.1     

* Icinga 2 version (`icinga2 --version`): r2.14.0-1
* Operating System: Debian GNU/Linux 11 (bullseye)
Kernel: Linux 5.10.0-26-amd64
* Webserver: apache2: 
Server version: Apache/2.4.56 (Debian)
Server built:   2023-04-02T03:06:01

**Comment by akellar** [comment] 2023-12-18 17:17
Looks like a duplicate of https://github.com/Icinga/icingaweb2-module-director/issues/2784#issue-1844690164

**Comment by nilmerg** [comment] 2024-01-18 08:50
Duplicate of #2784

**Closed by nilmerg** 2024-01-18 08:50 UTC
