### ISSUE TITLE
Import Preview doesn't show booleans correctly

### ISSUE THREAD

**Issue by swizzly** [Icinga/icingaweb2-module-director#981] opened 2017-06-27 07:40 UTC
In Import Preview the false boolean values are not displayed correctly, they are empty instead of "0", while true values are shown correctly as "1".
Please fix it.

**Comment by Thomas-Gelf** [comment] 2017-06-27 08:09
Thanks for reporting this, will be fixed!

**Comment by tobiasvdk** [comment] 2017-07-26 19:54
Looks like an duplicate of #602.

**Comment by Thomas-Gelf** [comment] 2017-07-27 08:38
Thanks @tobiasvdk, fixed for #602.

**Closed by Thomas-Gelf** 2017-07-27 08:38 UTC
Labels: bug
