### ISSUE TITLE
Bug in the Import->Sync.php

### ISSUE THREAD

**Issue by ikoabe** [Icinga/icingaweb2-module-director#810] opened 2017-02-21 16:23 UTC
The prepare function in the Sync.php contains a bug. I attached the Sync.php in this issue and leave in the file the description of the bug. 

`protected function prepare()
    {
        if ($this->isPrepared) {
            return $this->objects;
        }

        PrefetchCache::initialize($this->db);

        $this->raiseLimits()
             ->startMeasurements()
             ->fetchSyncProperties()
             ->prepareRelatedImportSources()
             ->prepareSourceColumns()
             ->loadExistingObjects()
             ->fetchImportedData();

        // TODO: directly work on existing objects, remember imported keys, then purge
        $newObjects = $this->prepareNewObjects();

        foreach ($newObjects as $key => $object) {

			// BUG::: Sometimes is the this->objects not a key value array and this condition has no effect. 
			// See the function: loadExistingObjects, this function is calling the other function with the name loadAllByType, that returns the existing objects by type from the database
			// loadAllByType is returning for the IcingaService object type a array without key value paar
			// In this bug case would insert a duplicate object in the database
            if (array_key_exists($key, $this->objects)) {
                switch ($this->rule->update_policy) {
                    case 'override':
                        $this->objects[$key]->replaceWith($object);
                        break;

                    case 'merge':
                        // TODO: re-evaluate merge settings. vars.x instead of
                        //       just "vars" might suffice.
                        $this->objects[$key]->merge($object);
                        break;

                    default:
                        // policy 'ignore', no action
                }
            } else {
            
			   //Original
			   //$this->objects[$key] = $object;
			   			
				
			   //Check if this->objects is not a key value array and the current object is as a object in the array.
			   if($this->objects != null && is_array($this->objects))
			   {
					$array_filter_results = array_filter($this->objects, function($obj) use($key) {
							//here we need the object_name as unique column, but it can be maybe a source->key_column
							return ($obj->object_name == $key);
					});

					if($array_filter_results != null && count($array_filter_results) > 0)
					{
					   continue;
					}
					else
					{
							$this->objects[$key] = $object;
					}
			   }
			   else
			   {
					 $this->objects[$key] = $object;
			   }
            }
        }

        $noAction = array();
        foreach ($this->rule->purgeStrategy()->listObjectsToPurge() as $key) {
            if (array_key_exists($key, $newObjects)) {
                // Object has been touched, do not delete
                continue;
            }

            if (array_key_exists($key, $this->objects)) {
                $object = $this->objects[$key];
                if (! $object->hasBeenModified()) {
                    $object->markForRemoval();
                }
            }
        }

        foreach ($this->objects as $key => $object) {
            if (! $object->hasBeenModified() && ! $object->shouldBeRemoved()) {
                $noAction[] = $key;
            }
        }

        foreach ($noAction as $key) {
            unset($this->objects[$key]);
        }

        $this->isPrepared = true;

        return $this->objects;
    }`

[Sync.zip](https://github.com/Icinga/icingaweb2-module-director/files/790730/Sync.zip)

**Comment by noudAndi** [comment] 2017-03-30 08:27
Looks like I'm hitting this bug right know. For which Version did you do this fix?

**Comment by nonsenseMB** [comment] 2017-03-30 10:27
The fix was made for v1.3.0

**Comment by Thomas-Gelf** [comment] 2017-03-31 11:54
Hi,

thanks for reporting this. I'm unable to reproduce the issue:

> Sometimes is the this->objects not a key value array [..]

Any idea how to reproduce this? We should IMHO then fix the root cause for this by making sure it always has the correct structure.

Thanks,
Thomas

**Comment by noudAndi** [comment] 2017-03-31 16:04
Hi,
@Thomas-Gelf : I'm not sure, if I can reproduce it once again. But if I can, what do you need to fix it (table dumps?)? To be honest, I'm more the Sysadmin-guy than the developer ;)

**Comment by Thomas-Gelf** [comment] 2017-03-31 16:11
In case you want me to reproduce an issue, the most efficient method is handing over a DB dump and telling me the exact version/git ref you're using. In case the DB contains confidential information either ship just a couple of tables and/or mask sensitive information. You could also ask me for a confidential/secured upload link if you want.

**Comment by noudAndi** [comment] 2017-03-31 16:43
Hi,
I will prepare the database, once I'm back in the office ;)

**Comment by Thomas-Gelf** [comment] 2017-05-03 10:24
ping @noudAndi :-)

**Comment by Thomas-Gelf** [comment] 2017-08-22 21:26
No feedback, closing this for now. Please feel free to re-open this or a new issue in case the problem persists.

**Closed by Thomas-Gelf** 2017-08-22 21:26 UTC

**Comment by noudAndi** [comment] 2017-08-23 07:09
Reopen!
@Thomas-Gelf : I sent you an email with all the details, hopefully you are able to reproduce the issue with these information.

**Comment by Thomas-Gelf** [comment] 2017-08-23 07:12
@noudAndi: you've got an answer containing a suggestion of how to fix this ;)
