### ISSUE TITLE
union method missing

### ISSUE THREAD

**Issue by inbaz** [Icinga/icingaweb2-module-director#862] opened 2017-03-18 08:00 UTC
The error message I get directly after installing the director module is:

```
Fatal error: Uncaught Error: Call to undefined method Icinga\Data\Db\DbQuery::union() in /usr/share/icingaweb2/modules/director/library/Director/Dashboard/Dashboard.php:159 Stack trace: #0 /usr/share/icingaweb2/modules/director/library/Director/Dashboard/Dashboard.php(130): Icinga\Module\Director\Dashboard\Dashboard->getObjectSummary(Array) #1 /usr/share/icingaweb2/modules/director/library/Director/Dashboard/Dashboard.php(91): Icinga\Module\Director\Dashboard\Dashboard->fetchDashletSummaries() #2 /usr/share/icingaweb2/modules/director/library/Director/Dashboard/Dashboard.php(64): Icinga\Module\Director\Dashboard\Dashboard->dashlets() #3 /usr/share/icingaweb2/modules/director/library/Director/Dashboard/Dashboard.php(69): Icinga\Module\Director\Dashboard\Dashboard->count() #4 /usr/share/icingaweb2/modules/director/application/controllers/DashboardController.php(33): Icinga\Module\Director\Dashboard\Dashboard->isAvailable() #5 /usr/share/icingaweb2/modules/director/application/controllers/IndexController.php(35): Icinga\Modu in /usr/share/icingaweb2/modules/director/library/Director/Dashboard/Dashboard.php on line 159
```

I thought DbQuery is using the zend-db adapter but with a view into the code I cannot find a connection to the zend-db adapter. Within the Class DbQuery and its parent classes the method union is not defined.

Is this a bug accoding to different version or did I miss anything?

Cheers
Andi

EDIT: Now I had another try in another plattform at the installation worked smooth. The difference: Ubuntu 16.04.2 (not working) vs. CentOS 7.3.1611 (working).

**Comment by rkopplin** [comment] 2017-03-23 10:44
same issue here: using Ubuntu 16.04.2

**Comment by Thomas-Gelf** [comment] 2017-03-23 10:48
What Icinga Web 2 version are you guys using? Does it met the Directors's [requirements](https://github.com/Icinga/icingaweb2-module-director/blob/master/doc/02-Installation.md#requirements)?

**Comment by rkopplin** [comment] 2017-03-23 11:01
Using: Server version: 5.7.17-0ubuntu0.16.04.1 (Ubuntu)
Icinga: 2.1.0
Director: 1.3.1
Icingaweb: r2.4.1-1
Curl: php7-curl since php5-curl is not available due php7

seems to be the same issue here as well. doesnt get it resolved with the workaround.
anything else seems to be working fine
https://monitoring-portal.org/index.php?thread/39890-director-dashboard-issue-resolved/

**Comment by rkopplin** [comment] 2017-03-23 11:05
#867

**Comment by dnsmichi** [comment] 2017-03-23 11:12
Icinga 2 v2.1.0? Guess that's wrong, try `icinga2 --version`.

If you're opening Icinga Web 2 and the notification history, does that work too?

**Comment by rkopplin** [comment] 2017-03-23 11:15
oh checked that at icingaweb2 about windows. seems to be wrong there, then.

> icinga2 - The Icinga 2 network monitoring daemon (version: r2.4.1-1)

Copyright (c) 2012-2015 Icinga Development Team (https://www.icinga.org)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: _CODENAME=xenia
  Platform version: CODENAME=xenia
  Kernel: Linux
  Kernel version: 4.4.0
  Architecture: x86_64


There are currently no notifications, but this seems to be no issue cause its a blank install few minutes ago.

**Comment by Thomas-Gelf** [comment] 2017-03-23 11:32
Blind guess: you're using what Ubuntu currently ships, that's Icinga 2.4.1 and Icinga Web 2.1.0. Both versions are very old, and lots of bugs have been fixed since then, lots of new features have been implemented.

Neither the Icinga (core) nor the web package meets the Director requirements I linked above. I'd strongly suggest to use our mirror to get the latest stable builds:

http://packages.icinga.org/ubuntu/

Cheers,
Thomas

**Comment by rkopplin** [comment] 2017-03-23 11:53
icinga2 is upgraded now.

seems that the upgrade is not working simply for icingaweb2. it will not upgrade due php-icinga is missing. 
and this will not get installed cause php5 is not available.

is icingaweb2 not working with php7?

**Comment by Thomas-Gelf** [comment] 2017-03-23 11:57
Icinga Web 2 works fine with PHP 7. Please check [Travis](https://travis-ci.org/Icinga/icingaweb2-module-director/builds/211359013) version-specific Director Unit Tests.

**Comment by rkopplin** [comment] 2017-03-23 13:43
seems to be something wrong here then.
using openvz and created 2 virtual machines with blank 16.04 image.
added the repo and tried to install icinga2.

icinga2 : Depends: icinga2-bin (= 2.6.2-1~ppa1~trusty1) but it is not going to be installed
E: Unable to correct problems, you have held broken package.

**Comment by rkopplin** [comment] 2017-03-23 14:08
confirmed. issue resolved by installing from scratch with icinga repo.
i guess this one can be closed.

**Closed** 2017-04-12 08:54 UTC

**Comment by plfiumi** [comment] 2017-05-17 21:48
Anyone knows how to solve this in Ubuntu 16.04.1? The user here doesn't solve the issue, just start a new installation. Thanks in advance!
