### ISSUE TITLE
unable to edit or clone a service check

### ISSUE THREAD

**Issue by thrashiii** [Icinga/icingaweb2-module-director#2411] opened 2021-10-12 12:26 UTC
## Current Behavior
when I want edit or clone a service apply rule or a service template a php error appears:

`Uncaught Error: Call to a member function toString() on null in /usr/share/icingaweb2/modules/director/application/controllers/ServiceController.php:249
Stack trace:
#0 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(465): Icinga\Module\Director\Controllers\ServiceController->loadObject()
#1 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(89): Icinga\Module\Director\Web\Controller\ObjectController->loadOptionalObject()
#2 /usr/share/icingaweb2/modules/director/application/controllers/ServiceController.php(41): Icinga\Module\Director\Web\Controller\ObjectController->init()
#3 /usr/share/php/Icinga/Web/Controller/ActionController.php(165): Icinga\Module\Director\Controllers\ServiceController->init()
#4 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(59): Icinga\Web\Controller\ActionController->__construct()
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(`

## Your Environment

* Director version (System - About): maser
* Icinga Web 2 version and modules (System - About): 2.9.3
* Icinga 2 version (`icinga2 --version`): r2.13.1-1
* Operating System and version: debian 9
* Webserver, PHP versions: apache 2.4.25-3+deb9u11, php 7.4

**Comment by Thomas-Gelf** [comment] 2021-10-14 07:40
Hi @thrashiii,

I'd love to - but I'm unable to reproduce this. The stack trace points to a place in the code, where we work with a discovered Service UUID. This is a compatibility feature, we're currently introducing UUIDs everywhere - while trying hard to not break existing APIs and URLs. It's tricky.

I definitively should add a check for "null" (the lookup is optional), but then the only correct answer would be 404. And that's probably not what you'd expect, as I assume that your service exists.

Do you have some details, allowing me to reproduce this? I tried to modify single services, override vars for inherited/applied ones, I successfully cloned services. How is this service defined, could you share screenshots of the form, the preview, the URL you're using to modify the service might help.

Thanks,
Thomas

**Comment by thrashiii** [comment] 2021-10-17 10:43
I have tested again: on a completly fresh test system I installed icinga2 with director. I created an empty database called "director" and created a new database schema in director. 

After this I created a new service template which was correctly created. If I now want to edit the created service template the php error appears. 

I hope this helps you.

**Comment by Thomas-Gelf** [comment] 2021-10-18 05:28
Should be fixed, thank you!

**Closed as completed** 2021-10-18 05:28 UTC

**Comment by Thomas-Gelf** [comment] 2021-10-18 08:19
Thank you so much for your patience and your valuable feedback, and sorry once again for the inconvenience and problems this caused.
