### ISSUE TITLE
Trying to recover from custom variable problem

### ISSUE THREAD

**Issue by terra-nova** [Icinga/icingaweb2-module-director#1601] opened 2018-08-13 14:05 UTC
## Expected Behavior

Hi,

after having fallen victim to the issue #1579, I have upgraded Icinga Director to 1.5.0 and downgraded Icinga2 to 2.8.4, however the overriding of custom variables still does not work like expected.

We have a host template `Host-IBM Power i`. This host template has a service set associated with it with some basic checks for CPU utilization, disk space, etc.

I want to override the default thresholds for disk utilization for hosts inheriting from the host template.

Host definition produced by Icinga Director:

```
object Host "xxxxxxxxx" {
    import "Host-IBM Power i"

    vars["_override_servicevars"] += {
        "System ASP" = {
            threshold_critical = "93%"
            threshold_warning = "90%"
        }
    }
```

Service definition as seen from Icinga2:

```
  * vars
    % = modified in '/var/lib/icinga2/api/packages/director/icinga.foo.bar-1534167899-3/zones.d/director-global/001-director-basics.conf', lines 43:7-43:51
    ...
    * threshold_critical = "90%"
      % = modified in '/var/lib/icinga2/api/packages/director/icinga.foo.bar-1534167899-3/zones.d/director-global/service_templates.conf', lines 60:5-60:35
    * threshold_warning = "80%"
      % = modified in '/var/lib/icinga2/api/packages/director/icinga.foo.bar-1534167899-3/zones.d/director-global/service_templates.conf', lines 61:5-61:34
```

So it seems that even after downgrading Icinga2 to 2.8.4 again, overriding custom variables does not work for service sets as it did before we upgraded Icinga2 to 2.9.1.

## Your Environment

* Director version (System - About): master as of today
* Icinga Web 2 version and modules (System - About): 2.6.1
* Icinga 2 version (`icinga2 --version`): 2.8.4
* Operating System and version: CentOS 7.5 x86_64
* Webserver, PHP versions: Apache 2.4, PHP 7.1 from RH SCL

**Comment by quentinsch** [comment] 2018-08-13 14:16
I also can confirm that the custom override function isn't fixed in v1.5.0. I upgrade my Director from master (505912135dd8ae728e0d6b8147beb6e423e97a12) to release v1.5.0, but my installation broke after this upgrade. The overrides didn't function anymore at all, even with service apply rules.
So not sure what is going on, but it still isn't fixed.
I reverted back to the master I backed up and it is working as expected.

When I did a config diff to see the changes I noticed it might has something to do with the global Director config (001-director-basics.conf):
```
const DirectorStageDir = dirname(dirname(current_filename))

globals.directorWarnedOnceForThresholds = false;
globals.directorWarnOnceForThresholds = function() {
    if (globals.directorWarnedOnceForThresholds == false) {
        globals.directorWarnedOnceForThresholds = true
        log(LogWarning, "config", "Director: flapping_threshold_high/low is not supported in this Icinga 2 version!")
    }
}

  const DirectorOverrideTemplate = "_override_servicevars"
if (! globals[DirectorOverrideTemplate]) {
  const DirectorOverrideVars = "host var overrides (Director)"

  globals.directorWarnedOnceForServiceWithoutHost = false;
  globals.directorWarnOnceForServiceWithoutHost = function() {
    if (globals.directorWarnedOnceForServiceWithoutHost == false) {
      globals.directorWarnedOnceForServiceWithoutHost = true
      log(
        LogWarning,
        "config",
        "Director: Custom Variable Overrides will not work in this Icinga 2 version. See Director issue #1579"
      )
    }
  }

  template Service DirectorOverrideTemplate ignore_on_error {
    /**
     * Seems that host is missing when used in a service object, works fine for
     * apply rules
     */
    try {
      if (! host) {
        var host = get_host(host_name)
      }
      if (! host) {
        globals.directorWarnOnceForServiceWithoutHost()
      }
    } except { globals.directorWarnOnceForServiceWithoutHost() }

    if (vars) {
      vars += host.vars[DirectorOverrideVars][name]
    } else {
      vars = host.vars[DirectorOverrideVars][name]
    }
  }
}
```
versus
```
const DirectorStageDir = dirname(dirname(current_filename))

globals.directorWarnedOnceForThresholds = false;
globals.directorWarnOnceForThresholds = function() {
    if (globals.directorWarnedOnceForThresholds == false) {
        globals.directorWarnedOnceForThresholds = true
        log(LogWarning, "config", "Director: flapping_threshold_high/low is not supported in this Icinga 2 version!")
    }
}

if (! globals["DirectorOverrideTemplate"]) {
  const DirectorOverrideVars = "_override_servicevars"
  const DirectorOverrideTemplate = "host var overrides (Director)"

  template Service DirectorOverrideTemplate ignore_on_error {
    /**
     * Seems that host is missing when used in a service object, works fine for
     * apply rules
     */
    if (! host) {
      var host = get_host(host_name)
    }

    if (vars) {
      vars += host.vars[DirectorOverrideVars][name]
    } else {
      vars = host.vars[DirectorOverrideVars][name]
    }
  }
}
```

**Comment by Thomas-Gelf** [comment] 2018-08-13 14:26
@terra-nova: could you please show me also the involved Service Objects/Apply Rules/Templates? Any warning in your Icinga 2 startup log?

**Comment by Thomas-Gelf** [comment] 2018-08-13 14:34
@quentinsch: that's strange, what Icinga 2 version are you running? Could you please show generated Object config for objects that do not work, an Apply Rule and a related Host object?

**Comment by quentinsch** [comment] 2018-08-13 14:55
@Thomas-Gelf, sure. I run Icinga2 version r2.9.1-1.

Host object:
```
object Host "xxxxxx" {
    display_name = "xxxxxx - Squid Proxy"
    address = "xxxxxx"
    check_command = "ping4"
    max_check_attempts = "6"
    check_period = "24x7"
    check_interval = 5m
    retry_interval = 2m
    check_timeout = 1m
    enable_notifications = true
    enable_active_checks = true
    enable_passive_checks = true
    enable_event_handler = true
    enable_flapping = true
    enable_perfdata = true
    volatile = false
    vars["_override_servicevars"] = {
        "NTP check" = {
            not_per = "never"
            nrpe_arguments = [ "ntp0.nl.net", "10", "60" ]
            nrpe_command = "check_ntp_time"
            nrpe_timeout = "60"
        }
    }
    vars.enable_pagerduty = "enabled"
    vars.host_roles = [ "apt-unattended-upgrades", "standard-linux-server" ]
    vars.not_per = "24x7"
    vars.par_host = "10.1.1.1"
    vars.ping_cpl = "90"
    vars.ping_crta = "1000"
    vars.ping_wpl = "75"
    vars.ping_wrta = "800"
    vars.slack_notifications = "enabled"
}
```

Service apply rule:
```
apply Service "NTP check" {
    import "check_nrpe-24x7"

    assign where "standard-linux-server" in host.vars.host_roles || "standard-linux-server-minimal" in host.vars.host_roles
    vars.not_per = "never"
    vars.nrpe_arguments = [ "ntp1.somewhere.local", "10", "20" ]
    vars.nrpe_command = "check_ntp_time"

    import DirectorOverrideTemplate
}
```

**Comment by Thomas-Gelf** [comment] 2018-08-13 15:04
@quentinsch: 2.9.1 is affected by above bug, however Apply Rules should be fine. Does your startup log (for the deployment in the Director frontend) show any warnings? The generated config looks good to me.

**Comment by quentinsch** [comment] 2018-08-13 15:10
@Thomas-Gelf: Ok, I'm going to deploy this configuration to the test environment to test it out in detail. I'll come back to you a.s.a.p. with the results.

**Comment by terra-nova** [comment] 2018-08-13 17:27
@Thomas-Gelf 
Also no warnings in the start up log that seem to pertain to this issue; just a bunch of warnings for apply rules not matching any object that are defined in the `global-templates` zone (e.g. not created or managed through Director).

**Comment by terra-nova** [comment] 2018-08-13 17:48
Downgrading Director to the level we had before updating to 1.5.0 (35815e0dad9bf7370a68f5128d17506b9a9530cb) fixes the custom variable problem for use (in conjunction with Icinga 2.8.4).

**Comment by terra-nova** [comment] 2018-08-13 18:29
@Thomas-Gelf 

No, not really.

* we were running Icinga 2.8.4 with Director `35815e0dad9bf7370a68f5128d17506b9a9530cb` before with no problems
* then, I (maybe foolishly) updated Icinga to 2.9.1 and Director to 1.5.0 at the same time, and ran into the problems described in issue #1579 
* I downgraded Icinga to 2.8.4, keeping Director at 1.5.0 -- this led to the problem with custom variables detailed in this issue
* only when I also downgraded Director to `35815e0dad9bf7370a68f5128d17506b9a9530cb` did the overriding of custom variables work again

I have had no time today to investigate further, unfortunately... just trying to get to a state where our on-call duty is not getting unneccessary calls at night ;-)

**Comment by Thomas-Gelf** [comment] 2018-08-13 18:33
Well, then stay with what works for you. In case there really is a problem I'll hopefully figure it out. If the combination of 1.5.0 with 2.8.4 would really cause a problem, that would be important for me to know. Are you sure you waited unless the next check result has been persisted when checking the outcome after downgrading from 2.9.1 to 2.8.4?

**Comment by terra-nova** [comment] 2018-08-13 18:38
@Thomas-Gelf 

Yes, I forced re-checks and made sure Icinga2 really did a recheck (by looking at the last check field) prior to examining the custom variables reported for the servies in question.

Thanks for the timely repsonse and all, it's nice to see Director improving all the time!

**Comment by Thomas-Gelf** [comment] 2018-08-14 06:32
@terra-nova, @quentinsch: I broke this when adding the log warning related to #1579 in fd372c6 :disappointed:. While I do not understand why the currently generated config is even valid, I'll immediately push a related fix.

**Closed** 2018-08-14 06:35 UTC

**Comment by Thomas-Gelf** [comment] 2018-08-14 06:41
Update: generated config was valid because it just switched the constants. Therefore not only the string has been changed, but also all import statements - and it was "valid" once again. However, the overridden vars on the hosts are not rendered based on the constant - and therefore did no longer match. So, Config was valid - but no overridden vars where there.

**Comment by quentinsch** [comment] 2018-08-14 07:53
@Thomas-Gelf: I can confirm that Director [v1.5.1](3c02f7499fe06299af083cb723be236555efaf93) fixed the override problem in my case using Service Apply rules. So everything works perfect now.
Thank you very much for your extra effort and patience regarding these issues!

**Comment by Thomas-Gelf** [comment] 2018-08-14 07:57
Glad to hear that, thanks for your help and your time! If nothing else pops up I'll tag a new release shortly.
