### ISSUE TITLE
hosts don't inherit servicesets from hosttemplates

### ISSUE THREAD

**Issue by bcogel** [Icinga/icingaweb2-module-director#740] opened 2017-01-23 15:40 UTC
I define basic sets of services for systems as servicesets and assign them to various hosttemplates. Those checks and the sets don't show up at hosts that import those hosttemplates.
When I assign the services directly to the hosttemplates, they are inherited by the hosts that import the templates

**Comment by bcogel** [comment] 2017-01-26 17:08
On closer examination: 
Hosts do inherit servicesets with hosttemplates. But the sets don't show up in the service tab in director. If I want to change parameters, I have to do it for all hosts in the hosttemplates where I import a set.
It would be nice if sets behave like services imported with hosttemplates.

**Comment by mbassett** [comment] 2017-01-27 19:37
sounds like dupe of #735

**Comment by Thomas-Gelf** [comment] 2017-02-16 10:45
It's definitively related to #735, but slightly different to fix.

**Closed** 2017-02-16 10:48 UTC
Labels: bug
