### ISSUE TITLE
Deployment occasionally fails to deploy with a white question mark.

### ISSUE THREAD

**Issue by andrewmiskell** [Icinga/icingaweb2-module-director#1813] opened 2019-03-28 13:35 UTC
## Expected Behavior
Successful deployment of configuration to Icinga2

## Current Behavior
Occasionally getting the following message on deployment:

"Unknown, failed to collect related information" and deployment has a white question mark.

Redeploying the same configuration a second time works without issue.

## Steps to Reproduce (for bugs)
Make configuration changes and click deploy, watch deployment and it fails with an unknown error.

## Your Environment
* Director version (System - About): 1.6.2
* Icinga Web 2 version and modules (System - About): 2.6.2
* Icinga 2 version (`icinga2 --version`): 2.10.4-1
* Operating System and version: CentOS 7.6.1810
* Webserver, PHP versions: https-2.4.6-88, php-7.1.8-1

ref/IP/13087

**Comment by lazyfrosch** [comment] 2019-04-02 07:23
This error appears when the stage was deployed, but could not be found when contacting the core on the next time.

Internally `stage_collected` should be set to `n` in this case.

Basically Director is doing this:
* Rending config as text
* Pushing this config as deployment stage to Icinga 2 (API)
* Waiting for Icinga to config test the stage and reload
* Director is pulling state from the API
  - Listing stages (this is missing the expected stage here)
  - Checking active stage
  - Reading `startup.log` and `status` from every stage (that has not been collected yet)
* State is stored in Director as stages will disappear from the core later

**Comment by lazyfrosch** [comment] 2019-04-02 07:37
Can you provide any log from Icinga 2 showing this issue?

**Comment by Thomas-Gelf** [comment] 2019-04-02 17:28
This is not an issue, at least not a Director issue. A configuration has been deployed to Icinga. For whatever reason, Icinga failed to complete config validation. This could happen because of bugs in former Icinga version or when a new deployment takes place while a former restart was still in progress. In such cases, Icinga placed no `status` and/or `startup.log` into the related staging directory.

There is no related timeout, but when Director figures out that a newer configuration is already running while an older one still provides no validation result, it considers this formerly deployed stage being orphaned. In that case it marks the deployment accordingly in it's database and removes the incomplete Stage via REST API from the Icinga node, because Icinga will not clean them up.

Cheers,
Thomas

**Comment by Thomas-Gelf** [comment] 2019-04-02 17:29
NB: I'll close this issue, but please do not hesitate to let us know in case you think this explanation doesn't fit what you're seeing!

**Comment by lazyfrosch** [comment] 2019-04-23 12:05
This issue seems to appear together with multiple timezones, when users in different timezones deploy config.

The code responsible is:

https://github.com/Icinga/icingaweb2-module-director/blob/4352264b73b3667fb6be069d8d4a12a9edb4920a/library/Director/Core/CoreApi.php#L685-L694

This is caused by #1332 and needs to be fixed in Director

**Closed** 2019-04-24 13:18 UTC
Labels: bug, ref/IP
