### ISSUE TITLE
Text not visible in theme modes dark and system with icinga web2 2.10.x

### ISSUE THREAD

**Issue by mdicss** [Icinga/icingaweb2-module-director#2519] opened 2022-04-07 16:14 UTC
## Expected Behavior
Text in text fields should be visible.

## Current Behavior
In Theme Mode Dark or System, most text written into text fields in the director is not visible as there is a white text on a white background. Theme Light is ok.

## Your Environment
* Director version (System - About): 1.9.0
* Icinga Web 2 version and modules (System - About): versions 2.10.0 and 2.10.1
* Operating System and version: Linux (centos 7)
* Webserver, PHP versions:

**Comment by nilmerg** [comment] 2022-04-08 06:19
Hi,

thanks for reporting, but this is a known issue.

**Comment by nilmerg** [comment] 2022-04-08 06:19
Duplicate of #2503

**Closed by nilmerg** 2022-04-08 06:19 UTC
