### ISSUE TITLE
Autocomplete of browser conflicting with autocomplete of Director

### ISSUE THREAD

**Issue by chrisg86** [Icinga/icingaweb2-module-director#1047] opened 2017-07-31 13:47 UTC
When creating a new host template, I noticed the `Check command` field is an autocomplete field. You __have to__ select a value from the list, otherwise a stacktrace is shown. For example try typing `htt` and click next to the box.

```
Failed to load icinga_command "ht"

#0 /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php(1078): Icinga\Module\Director\Data\Db\DbObject->loadFromDb()
#1 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php(506): Icinga\Module\Director\Data\Db\DbObject::load('ht', Object(Icinga\Module\Director\Db))
#2 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php(560): Icinga\Module\Director\Objects\IcingaObject->resolveUnresolvedRelatedProperty('check_command_i...')
#3 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php(596): Icinga\Module\Director\Objects\IcingaObject->getRelationId('check_command_i...')
#4 /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php(424): Icinga\Module\Director\Objects\IcingaObject->get('check_command_i...')
#5 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php(1154): Icinga\Module\Director\Data\Db\DbObject->getProperties()
#6 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php(965): Icinga\Module\Director\Objects\IcingaObject->resolve('Properties')
#7 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php(1023): Icinga\Module\Director\Objects\IcingaObject->resolveProperties()
#8 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php(955): Icinga\Module\Director\Objects\IcingaObject->getInherited('Properties')
#9 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php(2443): Icinga\Module\Director\Objects\IcingaObject->getInheritedProperties()
#10 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/IcingaObjectFieldLoader.php(253): Icinga\Module\Director\Objects\IcingaObject->toPlainObject(true)
#11 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/IcingaObjectFieldLoader.php(211): Icinga\Module\Director\Web\Form\IcingaObjectFieldLoader->removeFilteredFields(Array)
#12 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/IcingaObjectFieldLoader.php(50): Icinga\Module\Director\Web\Form\IcingaObjectFieldLoader->attachFieldsToForm(Object(Icinga\Module\Director\Forms\IcingaHostForm))
#13 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/DirectorObjectForm.php(392): Icinga\Module\Director\Web\Form\IcingaObjectFieldLoader->addFieldsToForm(Object(Icinga\Module\Director\Forms\IcingaHostForm))
#14 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/DirectorObjectForm.php(689): Icinga\Module\Director\Web\Form\DirectorObjectForm->addFields()
#15 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(496): Icinga\Module\Director\Web\Form\DirectorObjectForm->onRequest()
#16 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(508): Icinga\Module\Director\Web\Form\QuickForm->setRequest(Object(Icinga\Web\Request))
#17 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(367): Icinga\Module\Director\Web\Form\QuickForm->getRequest()
#18 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(171): Icinga\Module\Director\Web\Form\QuickForm->handleRequest()
#19 /usr/share/icingaweb2/modules/director/application/controllers/HostController.php(78): Icinga\Module\Director\Web\Controller\ObjectController->editAction()
#20 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Controllers\HostController->editAction()
#21 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('editAction')
#22 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#23 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#24 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#25 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#26 {main}
```

Besides this error, another flaw is that this field caches anything you ever typed into it and this auto-complete overlaps the auto suggest options. Apparently only in Google Chrome.

![image](https://user-images.githubusercontent.com/4715597/28780384-ca32d108-7606-11e7-9192-d17011d234bc.png)

## Expected Behavior
It shouldn't croak on invalid values, plus this field should have an `autocomplete="off"` property to avoid chrome autocomplete to overlay the actual suggestions.

## Current Behavior
A stacktrace is shown when sending invalid commands, as well as actual suggestions are hidden behind chrome suggestions.

## Possible Solution
Autosuggest issue can be easily solved by adding the `autocomplete="off"` property to the search box. Furthermore invalid commands should not be evaluated.

## Steps to Reproduce (for bugs)
1. Icinga Director -> Hosts -> Host templates -> Add
2. Type gibberish as a command in `Check command` below `Main properties`

## Context
Tried editing an existing host template.

## Your Environment
* Director version (System - About): 1.3.1
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): r2.6.3-1
* Operating System and version: Ubuntu 16.04.2 LTS
* Webserver, PHP versions: nginx/1.10.3 PHP 7.0.18

**Comment by Thomas-Gelf** [comment] 2017-07-31 16:06
Thanks for reporting this. I'm aware of the problem, just didn't have time to address it yet. It is however one of the issues that will be fixed before 1.4.0 is going to be tagged.

**Comment by chrisg86** [comment] 2017-08-01 05:39
Many thanks!

**Comment by lazyfrosch** [comment] 2017-08-01 11:24
This also affects imports, and possible more related input fields.

**Comment by Thomas-Gelf** [comment] 2017-08-22 16:16
While there are still some improvements for this kind of field in the pipeline, this error should no longer appear in current master.

**Closed by Thomas-Gelf** 2017-08-22 16:16 UTC
Labels: bug

**Comment by sahnd** [comment] 2017-08-23 08:01
I've just tested current master 71ab8b4 with Firefox and Chromium (Linux).
Typing some search string in "Imports" or "Check command" field and clicking on one of the displayed templates/commands still results in those errors. The clicked template/command is not put into the field afterwards.
Or did I misinterpret  what this issue is about?

**Comment by Thomas-Gelf** [comment] 2017-09-04 09:36
@sahnd: I'm unable to reproduce this, could you please share some related screen-shot?

**Comment by sahnd** [comment] 2017-09-05 06:52
I've just tried to reproduce this with 71057ef, but was not able to.
So I guess it has been resolved. :-)

**Comment by Thomas-Gelf** [comment] 2017-09-05 06:59
Thank you!

**Comment by Random2222** [comment] 2018-07-25 11:07
Hi, i'm faceing the same issue as @chrisg86 mentioned before.
As soon as i create a new host template, and try to type something in the "check command" field, the error appears.
The issue only appears with Firefox 61.0.1 , Microsoft Edge works fine.
