### ISSUE TITLE
Override of custom vars on applied servies for a single host is not possible

### ISSUE THREAD

**Issue by myownhost** [Icinga/icingaweb2-module-director#1575] opened 2018-07-19 13:45 UTC
## Expected Behavior

On applied services it was possible to overide custom service vars until git commit with hash 
d8b12072540bf5ebf8f8b1e43372d37cbabfb7a6

![grafik](https://user-images.githubusercontent.com/34742282/42944207-573b961a-8b65-11e8-9180-d9833144561f.png)

## Current Behavior

Since git commit with hash d5807495a03e0418ecc2bcdd73a8b902466732ae custom vars are not visible in Icinga Director on applied services. It's also the same behavior in current git master

![grafik](https://user-images.githubusercontent.com/34742282/42944536-310fe51c-8b66-11e8-9d89-47349b336289.png)

## Possible Solution

No idea

## Steps to Reproduce (for bugs)

Config from my template ping:
```
template Service "ping" {
    import "template"
    check_command = "ping"
    command_endpoint = null
    vars.ping_cpl = 50
    vars.ping_crta = 600
    vars.ping_wpl = 30
    vars.ping_wrta = 400
}
```

Config from apply rule
```
apply Service "ping" {
    import "ping"

    assign where host.address != "" && host.check_command != "dummy"

    import DirectorOverrideTemplate
}
```

## Your Environment

* Director version (System - About): master - 505912135dd8ae728e0d6b8147beb6e423e97a12
* Icinga Web 2 version and modules (System - About): 2.6.0
* Icinga 2 version (`icinga2 --version`): r2.9.0-1
* Operating System and version: Ubuntu 16.04.4
* Webserver, PHP versions: Apache/2.4.18, PHP 7.0.30

**Comment by Thomas-Gelf** [comment] 2018-07-20 07:01
I tried hard to reproduce this, but it works just fine for me. Could you please share more details and show where your fields have been attached. It would also be interesting to see where it breaks, read: where are the fields "lost"? Command, Service Template, Apply Rule - or just at Host level?

**Comment by myownhost** [comment] 2018-07-20 07:58
Thanks for the replay. The fields from the initial screenshots are on the host - services configuration - applied services - ping:
![grafik](https://user-images.githubusercontent.com/34742282/42990522-29c3eef0-8c03-11e8-87d9-37ddf4b1f923.png)


I try to give you an overview what i have configured in Icinga Director:

1. I created data fields for ping_cpl, ping_wpl, ping_crta and ping_wrta like in my screenshot
![grafik](https://user-images.githubusercontent.com/34742282/42989679-db99b338-8c00-11e8-90fb-e44ef7777493.png)

2. I created a service template named ping with the following parameters
![grafik](https://user-images.githubusercontent.com/34742282/42989838-384dc1be-8c01-11e8-99aa-7a35b7bca770.png)
![grafik](https://user-images.githubusercontent.com/34742282/42989915-70116e98-8c01-11e8-8690-f3fe4f425199.png)

3. My apply rule
![grafik](https://user-images.githubusercontent.com/34742282/42989986-a9f47cf4-8c01-11e8-905f-3301a3606927.png)

4. The command ping is external
![grafik](https://user-images.githubusercontent.com/34742282/42990214-62469a8a-8c02-11e8-8507-60112f8a0814.png)

Hopefully i don' forgot some detail.

Again many thanks for you hard work.

**Comment by Thomas-Gelf** [comment] 2018-07-20 10:58
Thanks for all the details... pretty strange, as that seems to be exactly what I did when trying to reproduce your issue. I'll try again...

**Comment by Thomas-Gelf** [comment] 2018-08-14 07:14
I believe this has been fixed in the current master with the fix for #1602.

**Closed by Thomas-Gelf** 2018-08-14 07:14 UTC

**Comment by myownhost** [comment] 2018-08-14 08:41
Many thanks. I can confirm that it ist working again with the new release.

**Comment by Thomas-Gelf** [comment] 2018-08-14 08:45
@myownhost: glad to hear that, thanks for testing it!
