### ISSUE TITLE
Creating Snapshot for Baskets with Dependencies fails

### ISSUE THREAD

**Issue by matthenning** [Icinga/icingaweb2-module-director#1739] opened 2018-12-13 15:08 UTC
## Current Behavior
An exception occurs: 
`Uncaught Error: Call to undefined method Icinga\Module\Director\Objects\IcingaDependency::getUniqueIdentifier() in /usr/share/icingaweb2/modules/director/library/Director/DirectorObject/Automation/BasketSnapshot.php:389`

Edit:
Full Stacktrace from the CLI:
```
~# icingacli director basket snapshot --name Full
PHP Fatal error:  Uncaught Error: Call to undefined method Icinga\Module\Director\Objects\IcingaDependency::getUniqueIdentifier() in /usr/share/icingaweb2/modules/director/library/Director/DirectorObject/Automation/BasketSnapshot.php:389
Stack trace:
#0 /usr/share/icingaweb2/modules/director/library/Director/DirectorObject/Automation/BasketSnapshot.php(133): Icinga\Module\Director\DirectorObject\Automation\BasketSnapshot->addAll('Dependency')
#1 /usr/share/icingaweb2/modules/director/library/Director/DirectorObject/Automation/BasketSnapshot.php(104): Icinga\Module\Director\DirectorObject\Automation\BasketSnapshot->addObjectsChosenByBasket(Object(Icinga\Module\Director\DirectorObject\Automation\Basket))
#2 /usr/share/icingaweb2/modules/director/application/clicommands/BasketCommand.php(63): Icinga\Module\Director\DirectorObject\Automation\BasketSnapshot::createForBasket(Object(Icinga\Module\Director\DirectorObject\Automation\Basket), Object(Icinga\Module\Director\Db))
#3 /usr/share/php/Icinga/Cli/Loader.php(265): Icinga\Module\ in /usr/share/icingaweb2/modules/director/library/Director/DirectorObject/Automation/BasketSnapshot.php on line 389
```

Upgrade process was:
```
wget https://github.com/Icinga/icingaweb2-module-director/archive/v1.6.0.zip
unzip v1.6.0.zip
cp -rf icingaweb2-module-director-1.6.0/* /usr/share/icingaweb2/modules/director/
```

Then running migrations from the frontend.

## Steps to Reproduce (for bugs)
Create a new Basket:
![grafik](https://user-images.githubusercontent.com/5699183/49947201-ec029b00-fef0-11e8-89a8-67dc98877e4a.png)

Click on Snapshots -> Create Snapshot:
![grafik](https://user-images.githubusercontent.com/5699183/49947224-fe7cd480-fef0-11e8-97a8-1690ac5d6a77.png)

## Your Environment

* Director version (System - About): 1.6.0
* Icinga Web 2 version and modules (System - About): 2.6.2
* Icinga 2 version (`icinga2 --version`): 2.10.2
* Operating System and version: Debian 9
* Webserver, PHP versions: nginx/1.10.3, PHP 7.2.13 (fpm)

**Comment by matthenning** [comment] 2018-12-13 15:13
Happens on current commit from `support/1.6` too.

**Comment by matthenning** [comment] 2018-12-13 15:24
Excluding Dependencies from the basket solves the problem.

**Comment by stevie-sy** [comment] 2019-01-23 06:14
We have the same problem in our Setup and get the same error messages. With the tipp from @matthenning - exclude the dependencies - it works fine. 

Our Setup:
•Director version (System - About): master branch updated yesterday
•Icinga Web 2 version and modules (System - About): 2.6.2
•Icinga 2 version (icinga2 --version): 2.10.2
•Operating System and version: CentOS 7.6.1810
•Webserver, PHP versions: httpd/2.4.6-88, php-fpm  7.1.8-1

**Comment by nbuchwitz** [comment] 2019-01-31 16:09
Same here.

The Problem is that https://github.com/Icinga/icingaweb2-module-director/blob/master/library/Director/Objects/IcingaDependency.php is not implementing the ``Icinga\Module\Director\DirectorObject\Automation\ExportInterface`` which methods are called by the export / import.

**Comment by Thomas-Gelf** [comment] 2019-02-12 10:50
Thanks @matthenning for reporting this and @nbuchwitz for pointing this out, will be fixed.

**Closed** 2019-02-14 20:55 UTC
Labels: bug
