### ISSUE TITLE
Unable to use constants in templates or commands

### ISSUE THREAD

**Issue by hniemann** [Icinga/icingaweb2-module-director#1075] opened 2017-08-12 19:23 UTC
Director 1.3.1
--

When I use constants in commands or command templates the constants always get quoted and dont get expanded
 
When I edit the the conf file by hand and remove the quotes and reload icinga2 the constants get expanded.

**Comment by dgoetz** [comment] 2017-08-16 10:06
This also hurts me when I want to define a commandline like `[ "/usr/bin/sudo" , PluginDir + "/command" ]`, which I did not manage to create at all. If I could hardcode the path instead of using PluginDir, it would be doable, but requiring the flexibility of PluginDir because of different os families in use I failed.

**Comment by cflinspach** [comment] 2017-08-16 13:04
Absolute paths are accepted as provided, relative paths are prefixed with "PluginDir + ", similar Constant prefixes are allowed. If you use the full path it won't add `PluginDir` so you can define your own. Here's two screenshots of one of our commands that we use sudo with. 

![director-sudo2](https://user-images.githubusercontent.com/4700533/29364416-2c78bf88-8248-11e7-8e4d-195fa8ec716e.png)
![director-sudo](https://user-images.githubusercontent.com/4700533/29364415-2c7637b8-8248-11e7-896c-3362d771bba5.png)

**Comment by dgoetz** [comment] 2017-08-16 13:14
@cflinspach: Thanks, but the problem is that I need PluginDir because of the different os families used here.

**Comment by cflinspach** [comment] 2017-08-16 13:17
@dgoetz so `PluginDir` would resolve to different paths based on the check source?

**Comment by dgoetz** [comment] 2017-08-16 13:20
@cflinspach: Yes, SLES uses arch-independent /usr/lib/nagios/plugins and RHEL uses arch-dependent /usr/lib64/nagios/plugins.

**Comment by gody01** [comment] 2018-06-21 09:35
+1 for use of Constants. Big problem with secure information. Now usernames/passwords has to be in the DB - not good.

**Comment by NeverUsedID** [comment] 2018-08-18 15:16
+1 :)

I think a rather easy solution would be to add some special syntax like {{{mystring}}} to avoid that the director placing quotes around that "string".

In my case i need that for auto creating the display_name:

`display_name = vars.location + "_" + vars.devicetype + "_" + vars.hostname`

Never found a way to configure this with the director.

**Comment by widhalmt** [comment] 2019-02-26 10:08
ref/NC/589957

**Comment by Linuxfabrik** [comment] 2020-05-08 12:42
Is there any news on this issue? Or is there another way of supporting different plugin directories on different operating systems?

**Comment by Thomas-Gelf** [comment] 2020-05-08 12:56
Hi @Linuxfabrik,

that's perfectly possible, has been fixed a long time ago. You can use `PluginDir` or other external constants:

![director_plugindir](https://user-images.githubusercontent.com/553008/81407036-f901d900-913a-11ea-8d55-ca002aa40bb0.png)

@cflinspach showed how to use `sudo`. What is not possible is having a constant "in the middle", like `BinDir + /sudo  + Plugindir + /check_plugin`. I'm not unhappy about this, as such a command is dangerous and should be the absolute exception and not the rule. You are forced to specify the plugin path in your sudoers file, so it shouldn't hurt to write the full path in the Icinga config too.

In case you really need a solution for that specific use-case please open a dedicated issue. I'll close this one for now - as what has originally been asked for has been implemented.

Cheers,
Thomas

**Closed by Thomas-Gelf** 2020-05-08 12:56 UTC
Labels: topic/support

**Comment by NeverUsedID** [comment] 2020-05-12 09:45
> +1 :)
> 
> I think a rather easy solution would be to add some special syntax like {{{mystring}}} to avoid that the director placing quotes around that "string".
> 
> In my case i need that for auto creating the display_name:
> 
> `display_name = vars.location + "_" + vars.devicetype + "_" + vars.hostname`
> 
> Never found a way to configure this with the director.

But i think, it still not solves this one, if I'am correct.
