### ISSUE TITLE
Autocomplete bug when trying to import template

### ISSUE THREAD

**Issue by camskkz** [Icinga/icingaweb2-module-director#1050] opened 2017-08-01 11:00 UTC
Hello, since a recent update we encounter a bug when a adding a new service to an host.

## Expected Behavior

When adding a new service to an host in the interface, typing the first few letters of the service template name in the Imports field will show the services templates corresponding to the search. Clicking on the name should auto complete the name of the service template and select it as an Import.

## Current Behavior

When typing the first few letters of the service template name, the list will show the corresponding services templates but clicking on one will not select it. Instead, it will try to import a service template named with only the first few letters typed before that does not exist.

## Possible Solution

To avoid this issue, we select the service template name with the keyboard arrows and press enter instead of clicking on it.

## Steps to Reproduce (for bugs)

1. Go to the Director interface
2. Select an host
3. Service -> add service
4. Type a few letters in the Import field
5. Select a service template corresponding to your search

## Context

This issues appeared with the recent update that changed some interfaces layout in the Icingaweb Director. We are currently up-to-date with the master branch.

## Environment

* Director version (System - About): v1.3.1, commit : 26fae33e6495a91a7da6a1ec4a68a03dd262c515
* Icinga Web 2 version and modules (System - About): v2.4.1, commit : 22feb4b3fdf9d2f79d3a6bb90d03bc0e04d64586, modules :
cube 1.0.0
fileshipper 1.0.0
monitoring 2.4.1
nagvis 1.1.1
translation 2.4.1
* Icinga 2 version (`icinga2 --version`): r2.6.3-1
* Operating System and version: Debian 7.11
* Webserver, PHP versions: Nginx 1.10, PHP 5.5.38

**Comment by lazyfrosch** [comment] 2017-08-01 11:23
Duplicate of #1047

**Closed by lazyfrosch** 2017-08-01 11:23 UTC
