### ISSUE TITLE
Unable to modify or delete fields assigned to host/service templates

### ISSUE THREAD

**Issue by terra-nova** [Icinga/icingaweb2-module-director#726] opened 2017-01-18 14:06 UTC
Hi,

with the current Git repository (HEAD 7b776956e374ac6b0a91e7c8f4bd01d76569b118), I cannot edit or remove fields assigned to host or service templates.

The currently assigned fields are all grayed out. I used to be able to modify or delete them.

![unbenannt](https://cloud.githubusercontent.com/assets/16338849/22067014/b0ffbb16-dd8f-11e6-89ba-479e10c61452.PNG)

My DB is on PostgreSQL 9.2.

Kind Regards.

**Comment by Thomas-Gelf** [comment] 2017-01-18 14:28
They have been inherited either from another template or from a command I guess. In that case this is the desired behavior, you have to change them where they have been assigned.

**Comment by terra-nova** [comment] 2017-01-18 14:44
Unfortunately, that is not the case -- all our checkcommands are defined outside of Director, thus we have no fields associated with checkcommands. The first field in the screenshot ("os400_asp_number") has been linked to the service template being edited. It's a kind of disk utilization check for IBM i (AS/400) systems, so the field doesn't make sense for any other service...

**Comment by Thomas-Gelf** [comment] 2017-01-18 16:17
It is perfectly legal to assign fields to check commands, even if defined outside of Director. Could you please double-check this, got to the fields page of every template inherited directly or indirectly by this service, same for their commands?

Otherwise we need either more screenshots or some SQL voodoo. I want to believe you, just - I'm unable to reproduce this. Yesterday and this morning I worked on a nice example for the documentation that involved a lot of fields - would have been impossible with this issue. You can see the result here: [Fields example - SNMP](https://github.com/Icinga/icingaweb2-module-director/blob/master/doc/16-Fields-example-SNMP.md)

**Comment by terra-nova** [comment] 2017-01-19 09:34
I do not have much time to figure out a recursive SQL query right now, so screenshots will have to do :-)

a) There are no fields associated with checkcommands (although it may be a good idea to do so, hm....)

b) Service Template "IBM i: ASP Utilization" imports template "Service-Checkccd", which in turn imports template "Service".

![st_asp_utilization](https://cloud.githubusercontent.com/assets/16338849/22101017/d9212c9a-de31-11e6-8757-c6cc8ae52216.PNG)

![st_checkcc](https://cloud.githubusercontent.com/assets/16338849/22101020/dce25444-de31-11e6-9572-36469cd9750c.PNG)

![st_service](https://cloud.githubusercontent.com/assets/16338849/22101044/f1410278-de31-11e6-9276-a8b57b5a693e.PNG)

c) Fields associated with template "Service":

![st_service_fields](https://cloud.githubusercontent.com/assets/16338849/22101107/41b7a162-de32-11e6-88c9-d0f440ff05c2.PNG)

I cannot edit or delete any of the associated fields. I used to be able to select one of the associated fields and change the optional/mandatory setting, or remove the association with the service template altogether.

The derived service templates each add a few additional fields, but since I cannot even manipulate the fields associated with the base template, surely something is not right?!

Kind regards

**Comment by erezzarum** [comment] 2017-01-26 10:33
I can confirm this, i just created a field and at the same time, i can't edit it, it grey out immediately :(

**Comment by Thomas-Gelf** [comment] 2017-01-26 11:01
Strange... I tried hard, but I'm still unable to reproduce this. Any chance one of you could send me a related DB-dump in private? I'll treat it confidentially, but still please eventually remove sensitive data first.

Thanks,
Thomas

**Comment by erezzarum** [comment] 2017-01-26 19:16
Do you try and delete it from the main datafields or from an object?
I can't send the DB dump, it will be too risky for me to filter it, i'm sorry :( (As much as i want to have it fixed)

**Comment by mbassett** [comment] 2017-02-06 19:14
This exact same behavior happens with importing commands that already have fields enabled.

![image](https://cloud.githubusercontent.com/assets/2250654/22662313/5e506dfc-ec5d-11e6-95af-c237abe86013.png)


![image](https://cloud.githubusercontent.com/assets/2250654/22662332/70824536-ec5d-11e6-8c56-185f036139f2.png)

![image](https://cloud.githubusercontent.com/assets/2250654/22662349/7db66020-ec5d-11e6-8489-ad86a7eef3ff.png)

**Comment by zearan** [comment] 2017-02-08 07:55
Hi Thomas,
I could prepare a dump which is stripped of sensitive information (PostgreSQL). Where do I have to send it?

**Comment by zearan** [comment] 2017-03-09 11:44
Do you still require a dump for this? I would like to see this fixed and can prepare one.

**Comment by YenzRanger** [comment] 2017-03-15 14:52
I had the exact same issue (with a new setup) and can confirm that this is an issue with PostgreSQL. Installing everything from bottom up again, but using MySQL instead of PostgreSQL has fixed this.

**Comment by isnotnull** [comment] 2017-04-24 12:07
I just deleted them from the DB table 'icinga_service_field', so far no side effect.

**Comment by Thomas-Gelf** [comment] 2017-04-24 12:13
@isnotnull: thanks for the information.
@zearan: in case this is still an issue: yes, absolutely - it needs to be fixed.

**Comment by Thomas-Gelf** [comment] 2017-04-24 12:14
Hint for myself: as @YenzRanger pointed out, this might be an issue affecting only PostgreSQL.

**Comment by groundop** [comment] 2017-07-18 16:15
I also faced this issue with a PostgreSQL setup and had quick look in the "fields assigned to host templates" part, to find that the tables for fields both in hosts and services are created at the same piece of code.

As far as I could understand, within `application/tables/IcingaObjectDatafieldTable.php` there are two checks whether a field is directly defined in the currently displayed template (and should be thus edit-able and delete-able) or in a parent template and thus should be neither:
(Comments by me)
```PHP
# Assign the URL for editing this field iff it is included in this template
protected function getActionUrl($row)
{
    if ($row->object_id !== $this->object->id) {
        return null;
    }
    return Url::fromRequest()->with('field_id', $row->id);
}    

# Grey out the row if the field is defined in a parent template
protected function getRowClasses($row)
{
    if ($row->object_id !== $this->object->id) {
        return array('disabled');
    }
}
```
Unfortunately, after inserting some debugging code to smuggle out the values and types of those compared IDs...

```PHP
protected function getRowClasses($row)
{
    if ($row->object_id !== $this->object->id) {
        #return array('disabled');
        return array($row->object_id,'-',gettype($row->object_id),' ',$this->object->id,'-',gettype($this->object->id));
    }
}
```
... it appears that the types of the IDs do not match:
```html
<tr class="3 - integer   3 - string" href="correct_link">
```
Unfortunately my PHP knowledge and pratice are both fairly low and I'm unsure how / where to proceed. One _could_ omit the type-testing comparison, but AFAIR that summons evil things in projects.
Since this problem was only reported from PostgreSQL users, is it possible that PostgreSQL reports the wrong data types back when queried?
Could perhaps someone cross check if the types are ok when using MySQL?

**Comment by groundop** [comment] 2017-07-18 21:51
@sysadmama helped me out and got some debug output of a director installation using MySQL, as her screenshot shows the types of both IDs are String. (that is counter-intuitive to me, but hey typing and PHP.)

![icinga-director-object-field-types](https://user-images.githubusercontent.com/30267405/28341252-249a8a08-6c13-11e7-8bcb-ffe0b1f3fbfa.png)

**Comment by Thomas-Gelf** [comment] 2017-07-18 21:56
@groundop: hey, that's a good catch! Could you please try to replace those comparisons as follows...

```patch
- if ($row->object_id !== $this->object->id) {
+ if ((int)$row->object_id !== (int)$this->object->id) {
```

...and let me know whether this solves the problem?

**Comment by Thomas-Gelf** [comment] 2017-07-18 21:57
NB: You need to change this both in `getRowClasses()` and `getActionUrl()`

**Comment by groundop** [comment] 2017-07-19 10:04
Yes, that seems to solve the problem - I now can update and delete (only the) fields included at that host / service template and see all those of parent templates.

**Comment by lazyfrosch** [comment] 2017-07-20 09:04
@Thomas-Gelf need a PR for this? or already on your agenda?

**Comment by Thomas-Gelf** [comment] 2017-07-20 09:18
@lazyfrosch: no need for a PR, thank you :-) I's just the one-liner above, well, twice. As you probably noticed I'm currently pushing re-factored table after table to `next`. A PR would be more confusing than helpful at the time being, especially as i have above fix already in my workdir. Today I'll merge next into master, this will make things easier.

**Comment by Thomas-Gelf** [comment] 2017-07-20 09:19
NB: and welcome back!

**Closed** 2017-07-20 15:31 UTC
Labels: bug
