### ISSUE TITLE
deployment hangs forever

### ISSUE THREAD

**Issue by brad-plumewifi** [Icinga/icingaweb2-module-director#1488] opened 2018-05-15 02:44 UTC
## Expected Behavior
click deploy, deploy either succeeds or fails.

## Current Behavior
status wheel spinning and says status "Unknown, still waiting for config check outcome"

## Steps to Reproduce (for bugs)
Click on re-deploy for a specific version and it hangs.
Tried restarting Icinga2, upgrading director, restarting apache2, different web browsers, logout/log back in.
Tried adding '?checkforchanges' as referenced in a previous bug, and didn't work.  

## Your Environment

* Director version (System - About): master
* Icinga Web 2 version and modules (System - About): 2.5.1
* Icinga 2 version (`icinga2 --version`): r2.8.1-1
* Operating System and version: Ubuntu 16.04.3
* Webserver, PHP versions: 
apache2                              2.4.18-2ubuntu3.5
php7.0                               7.0.22-0ubuntu0.16.04.1

**Comment by akqopensystems** [comment] 2018-06-08 09:49
+1

**Comment by bleizg** [comment] 2018-07-26 12:59
+1

**Comment by geotekberlin** [comment] 2018-08-13 16:15
Upgrading to Director 1.5.0 did not solve the issue.  :-(

**Comment by geotekberlin** [comment] 2018-08-13 18:40
Yes. I cloned my Icinga2 server and downgraded Icinga2 to 2.8.0 and I can reproduce the effect.

**Comment by Thomas-Gelf** [comment] 2018-08-13 18:49
@geotekberlin: that's... weird. I tried here with both 2.9.1 and 2.8.4 on Debian, unable to reproduce the issue. Does this also happen on CLI with:

```sh
icingacli director config deploy --force --debug --benchmark
```

**Comment by Thomas-Gelf** [comment] 2018-08-13 18:53
Oh, and in any case - please show the output of that command

**Comment by geotekberlin** [comment] 2018-08-14 07:44
Forced deployment from the console works fine without errors (see attachment). This deployment also shows up correctly on the GUI, Host and service changes are correctly deployed to Icinga but the deployment icon still keeps spinning. Status is "Unbekannt, warte auf Ergebnis der Konfigurationsprüfung". 
[icingacli_deploy_config_2018-08-14.txt](https://github.com/Icinga/icingaweb2-module-director/files/2285881/icingacli_deploy_config_2018-08-14.txt)

From my memory this mess started after I deleted some users and host groups from the Director GUI that were no longer needed. Deployment worked fine witnhout any errors but from then on verification never ended. I suspect that some of these hostgroups and users still had assignments bound to them, so I rolled back the configuration, but to no avail. Also recreating the deleted host groups and users did not solve the issue. Maybe this is only a coincidence but maybe it could help to find the underlying issue.

**Comment by Thomas-Gelf** [comment] 2018-08-14 07:51
@geotekberlin: what operating system, web server, PHP version are you running? Could you please also show me the Icinga log during a deployment?

**Comment by geotekberlin** [comment] 2018-08-14 08:33
Voila:
[Versions.txt](https://github.com/Icinga/icingaweb2-module-director/files/2286115/Versions.txt)
[icinga2-log-during-deployment.txt](https://github.com/Icinga/icingaweb2-module-director/files/2286122/icinga2-log-during-deployment.txt)

**Comment by Thomas-Gelf** [comment] 2018-08-14 08:39
Thanks! Others on this issue: are you also running OpenSuse?
@geotekberlin: what does your /var/lib/icinga2/api/packages/director/ directory look like?

**Comment by geotekberlin** [comment] 2018-08-14 08:53
![grafik](https://user-images.githubusercontent.com/15341250/44081709-a9026de4-9faf-11e8-9029-2a687e767b25.png)
[director-api-configs.zip](https://github.com/Icinga/icingaweb2-module-director/files/2286183/director-api-configs.zip)

**Comment by rojobull** [comment] 2018-08-14 10:53
I’m running on CentOS 7.4...

pventurini@bamfunds.com<mailto:pventurini@bamfunds.com> | Balyasny Asset Management


________________________________

**Comment by akqopensystems** [comment] 2018-08-14 12:52
We are on RHEL 7.5 | Icinga2 2.8.4 | Icingaweb2 2.5.3 | Director 1.4.3

**Comment by geotekberlin** [comment] 2018-08-14 16:13
One interesting observation: Without any change in the Icinga2 environment all of a sudden **one and only one deployment** succeeded with a green icon. I haven't seen this for weeks now. All following deployments with minimal changes fail again, however. Which leads me to suspect a timing / timeout issue. 

Lack of computing resources can't be the reason though. Server has 90% free CPU, runs on SSD volumes and has a blindingly fast GUI response.

**Comment by Thomas-Gelf** [comment] 2018-08-14 17:00
I'm unable to reproduce this, so I need your help here. First of all, `netstat -antp | grep 5665` before/during/after deployment on an affected box could provide some insight.

Next, we could try to patch Director in a way immediately/forcibly closing HTTP connections. Please open `library/Director/Core/RestApiClient.php` and try as follows:

a) on line 138:
```patch
             'Host: ' . $this->getPeerIdentity(),
             // 'Connection: close'
         );
+        if (! $stream) {
+            $headers[] = 'Connection: close';
+        }
 
         if (! $raw) {
             $headers[] = 'Accept: application/json';
```

b) on line 151:

```patch
         $curl = $this->curl();
         $opts = array(
             CURLOPT_URL            => $this->url($url),
             CURLOPT_HTTPHEADER     => $headers,
+            CURLOPT_FORBID_REUSE   => 1,
             CURLOPT_USERPWD        => $auth,
             CURLOPT_CUSTOMREQUEST  => strtoupper($method),
```

Try first one, then the other, eventually both together. Please note that in case it works I do not consider this a viable solution, as not keeping connections open means performing worse. But it will help us to track down this issue.

And, out of curiosity: you do not have auto-refresh disabled in your Icinga Web 2, do you?

**Comment by geotekberlin** [comment] 2018-08-14 21:05
Here are the netstat results:
[netstat.zip](https://github.com/Icinga/icingaweb2-module-director/files/2288467/netstat.zip)
I applied the patches one after the other and both together but nothing changed.
Auto-refresh isn't disabled.

**Comment by widhalmt** [comment] 2018-09-13 09:40
I'm not totally sure if this is related but someone told me about similar problems with different versions of all included tools (even different Linux distributions). Unfortunately their ops people fixed the problems by restarting the host and didn't keep any logs.

But we had a similar experience right now with a newly setup master.
The most significant things which might have lead to several deploys hanging:

* Many deploys within a short range of time
* Apply rules combinded with `AND` and using `!=`

At a first glance we didn't realize what was going wrong because Director showed us everything fine. The only strange thing was that the last deploy from the log was about 1h old. Using `icingacli director health` we saw that a deploy was still pending.

The environment is object to many changes right now, I can't apply patches, especially because this happens rather rarely. But I can provide you with more details if you need some.

ref/NC/558885

**Comment by cptnkoiz** [comment] 2018-09-13 09:44
same here, up to date centos,php, director from master, etc.

what started the issue was two director deployments within 2 seconds. So two deployments are with the spinning circle, but all deployments after that were fine.

Apply rules were not involved in my case.

**Comment by geotekberlin** [comment] 2018-09-30 12:43
Updating to Icinga 2.9.2 did not resolve the issue. Deployment still works but only about one out of roughly 20 deployments gets randomly a green check symbol, all others remain spinning indefinitely.
Similarly to what cptnkoiz said I also remember that this whole problem started after I did two deployments in rapid succession.

**Comment by Thomas-Gelf** [comment] 2018-10-05 12:53
Sorry for the delay, I finally found someone who helped me to reproduce this. This happens only when you manage it to ship a deployment while Icinga 2 is already preparing to restart with a deployed configuration. If this happens often, you should check for something weird in your setup. Duplicate Jobs, automation tasks, whatever.

As this is probably hard to fix in the Core itself I implemented a workaround detecting two variants of this issue. Director then not only corrects the state of it's deployment, but also wipes the incomplete Icinga Stage via API from the Icinga node.

Fix is ready, will be pushed within minutes.

**Closed** 2018-10-05 12:55 UTC
Labels: bug

**Comment by Thomas-Gelf** [comment] 2018-10-06 13:31
@geotekberlin: while this fix should deal with deployments "forgotten" by Icinga 2, the numbers shown by you (like "only one out of twenty deployments succeeds") are irritating. Please let me know how this worked out for you, in your scenario there might be something else causing trouble. Or you have just too many old unfinished deployments and your Icinga Core is therefore unbelievable slow on restart - we'll see.

**Comment by geotekberlin** [comment] 2018-10-07 20:19
Hi Thomas, unfortunately the current master did not resolve the issue. I don't think this has to do with iconga slowness, however. All deployments are finished after 3 seconds and in the (unlikely) event that the green symbol appears, it shows up almost immediately.
With the current master, however, I get a bunch of orange warning messages after deployments like the ones enclosed. Do I have to worry about this?
 
[deployment_warnings.zip](https://github.com/Icinga/icingaweb2-module-director/files/2454281/deployment_warnings.zip)

**Comment by Thomas-Gelf** [comment] 2018-10-08 07:28
NB: for the sake of clarity, Director fails to store the startup log - not the file itself. While it would be possible to add some magic allowing for invalid encodings to be detected, I'm against doing so. Seen from a security perspective it would be very dangerous, encoding issues should be fixed at their root. Windows XP is long time dead, so I see no more justification for allowing anything but UTF8 at all. And please don't ask for UTF16 ;-)

**Comment by geotekberlin** [comment] 2018-10-08 18:09
Hi Thomas, you helped me get onto the right track and after a year of unsuccessful troubleshooting the problem is finally solved!!!!

Since my manually created /etc/icinga2/conf.d/notifications.conf is completely empty I wondered where this umlaut string is coming from but could not find it anywhere except in all the accumulated configs in \var\lib\icinga2\api\packages\director. I then decided to delete this folder completely and guess what - The green apply symbol is back immediately after each manual application. Most interesting is that at the same time ALL the yellow warning messages are also gone! So it looks like the two effects did indeed belong together somehow. Obvioulsy director got stuck while processing the contents of this corrupted directory but this went unnoticed until the current master which showed warnings.

Thanks a lot for your help!

**Comment by Thomas-Gelf** [comment] 2018-10-10 06:56
@geotekberlin: you're welcome! Guess you had something in that file some time ago and Icinga placed malformed startup log output to it's var directory. The Director has been being unable to persist it, the database refused it as of it's wrong encoding. It would be great if someone could find the time for an attempt to reproduce this issue step by step, with the goal of creating a related Icinga 2 issue afterwards.

In my believes, Icinga shouldn't accept invalid encodings on any of it's interfaces - and definitively it shouldn't ship such. Unfortunately I'm too busy with other tasks right now, and you're the first one with such symptoms. I roughly explained the issue to my colleagues, they'll try to tackle the "we should not accept malformed text at all" in a more generic way.

Cheers,
Thomas
