### ISSUE TITLE
Dark theme is not showing information in sidebar in director

### ISSUE THREAD

**Issue by firatalkis** [Icinga/icingaweb2-module-director#2517] opened 2022-04-07 11:39 UTC
I can not see configuration item properties in director configuration host or service...

![image](https://user-images.githubusercontent.com/42132281/162190561-34007477-397d-4757-a0e3-dff5722af170.png)

![image](https://user-images.githubusercontent.com/42132281/162190688-02ce41ce-f8a5-4ce1-b4b4-1deef4237cdb.png)

**Comment by nilmerg** [comment] 2022-04-07 12:09
Hi,

thanks for reporting, but this is a known issue.

**Comment by nilmerg** [comment] 2022-04-07 12:09
Duplicate of #2503

**Closed by nilmerg** 2022-04-07 12:09 UTC
