### ISSUE TITLE
Cant't create usergroup because of invalide property assign_filter

### ISSUE THREAD

**Issue by Jan-Schuppik** [Icinga/icingaweb2-module-director#2784] opened 2023-08-10 08:33 UTC
## Expected Behavior
I would like to create a usergroup 

## Current Behavior
If i tried, it fails
![Screenshot from 2023-08-10 10-23-30](https://github.com/Icinga/icingaweb2-module-director/assets/114286749/c69f5c54-0199-4a35-ae6b-1c60b3ffbe88)

## Your Environment
* Director version (System - About): f3455c197dc76f8761a9e147eb1b927a090f6074
* Icinga Web 2 version and modules (System - About): 2.11.4
* Icinga 2 version (`icinga2 --version`): 2.14.0
* Operating System and version: ubuntu 22.04
* Webserver, PHP versions: apache2 2.4.52, mod_php 8.1.2

**Comment by BalawalSultan** [comment] 2023-09-20 08:45
Hi @Jan-Schuppik,
I was facing a similar issue and found the cause. 
This is caused by the commit: [IcingaObjectGroup: membership calculation is now being triggered only when assign_filter exists / has been changed](https://github.com/Icinga/icingaweb2-module-director/commit/48af679cf0695e846085966eb293cd7f84041478?diff=unified#diff-7dd2f5a978c87115390f99c03aa1723898072896f0a2c5269fdc2a61343e17dcR42) 

The `$this->get('assign_filter')` throws an exception because the `IcingaUserGroup `class (Contact group in GUI) has no property called 'assign_filter'. It is correct that `IcingaUserGroup` doesn't have this property because you have no good reason to assign services using a usergroup.

This commit makes this check for every object that inherits from the `IcingaObjectGroup` class, which is not correct.
To fix this behaviour you can change the `beforeStore` method in the `IcingaObjectGroup` class as such
```bash
protected function beforeStore(){
        parent::beforeStore();
        if ($this->hasBeenLoadedFromDb()) {
            if (!array_key_exists('assign_filter', $this->getModifiedProperties())) {
                $this->memberShipShouldBeRefreshed = false;
                return;
            }
        } else {
            if(get_class($this) != 'Icinga\Module\Director\Objects\IcingaUserGroup'){
                if ($this->get('assign_filter') === null) {
                    $this->memberShipShouldBeRefreshed = false;
                    return;
                }
            }else{
                $this->memberShipShouldBeRefreshed = false;
                return;
            }
            
        }

        $this->memberShipShouldBeRefreshed = true;
}
```

**Comment by Yoda-BZH** [comment] 2023-09-27 07:15
@Jan-Schuppik hello, is this fix still valid against 76509bb7c81b43613c3f00a7ee1bd3829e19c8aa ?

Tried it, and still have the error. Apparenlty the error is thrown when `parent::beforeStore()` is called.

**Comment by Yoda-BZH** [comment] 2023-09-27 07:19
Moving `parent::beforeStore()` at the end of the function seems to fix the problem

**Comment by BalawalSultan** [comment] 2023-09-27 07:46
> @Jan-Schuppik hello, is this fix still valid against [76509bb](https://github.com/Icinga/icingaweb2-module-director/commit/76509bb7c81b43613c3f00a7ee1bd3829e19c8aa) ?

I have not tried that version of Icinga Director, but looking at the code I assume that the issue is still present.

> Tried it, and still have the error. Apparenlty the error is thrown when `parent::beforeStore()` is called.
Yes you are right, I made a mistake while copying the solution. If we call `parent::beforeStore()` we are calling the `beforeStore` method of the `IcingaObjectGroup` class, which is the method that gives us an error.

I do not know why placing `parent::beforeStore()` at the end of the method solves the issue, because you are still calling the  `beforeStore ` method of the `IcingaObjectGroup`. Ideally we would want to call the `beforeStore` method of the parent class of  `IcingaObjectGroup `. 

To get the idea across, what we need should be something like `parent::parent::beforeStore()`, but this is not valid PHP. 

So you could try this inside `IcingaUserGroup`
```
//I got this from IcingaObject which is the parent class of IcingaObjectGroup 
protected function GrandParentBeforeStore(){
    $this->resolveUnresolvedRelatedProperties();
    if ($this->gotImports()) {
        $this->imports()->getObjects();
    }
}

protected function beforeStore(){
        $this->GrandParentBeforeStore();
        if ($this->hasBeenLoadedFromDb()) {
            if (!array_key_exists('assign_filter', $this->getModifiedProperties())) {
                $this->memberShipShouldBeRefreshed = false;
                return;
            }
        } else{
                $this->memberShipShouldBeRefreshed = false;
                return;
        }

        $this->memberShipShouldBeRefreshed = true;
}
```
I do not know if this will work, but it's the solution that came to mind.

**Comment by tbauriedel** [comment] 2023-11-29 12:05
ref/NC/791877

**Comment by kbucheli** [comment] 2023-12-15 10:23
Hm, I now realized that the [latest fix would be by @BalawalSultan](https://github.com/Icinga/icingaweb2-module-director/issues/2784#issuecomment-1736878097), but here is the same issue as above (incl. the same stack trace):
- first sync works
- second sync errors

**Comment by nilmerg** [comment] 2024-01-16 08:50
@Thomas-Gelf Are you still working on this?

**Comment by Thomas-Gelf** [comment] 2024-01-18 08:49
@nilmerg: I've been told to not move my fingers unless being asked to do so. Unfortunately we missed this issue, before tagging v1.10. I made a quick fix for this shortly after the release, as colleagues faced this issue in an Icinga training - it then worked as expected. Should I create a related PR?

Cheers,
Thomas

NB: I removed my assignee-tag from all issues, to avoid confusion.

**Comment by nilmerg** [comment] 2024-01-18 09:05
Yes. Please.

**Comment by Thomas-Gelf** [comment] 2024-01-18 09:15
PR is there - should fix the issue. In future, implementing assignments for user groups too might be an option

**Closed** 2024-01-19 11:29 UTC
Labels: bug, ref/NC
