### ISSUE TITLE
Zone configuration overriden when using apply rules

### ISSUE THREAD

**Issue by matthenning** [Icinga/icingaweb2-module-director#1621] opened 2018-09-03 11:36 UTC
I encountered an issue when trying to deploy a service with a defined zone using an apply rule.

## Expected Behavior
If I define a zone for a service and apply it using an apply rule in Director the service is deployed accordingly and is executed in the defined zone even when applied to hosts in other zones.

## Current Behavior
The zone is overriden and the service stays `pending` forever. Config checks succeed.
This seems to occur if either the apply rule or the template is configured in director. If thy are both defined in /etc/icinga2/zones.d/master it works.

Director template preview:
```
zones.d/master/service_templates.conf

template Service "REMOTE ES Query Automic Broken Pipe" {
    check_command = "check_elasticsearch_query"
    max_check_attempts = "3"
    check_interval = 30s
    retry_interval = 30s
    check_timeout = 30s
    enable_notifications = true
    enable_active_checks = true
    enable_passive_checks = true
    enable_event_handler = true
    enable_perfdata = true
    zone = "master"
    icon_image = "automic.png"
    command_endpoint = null
}
```

### When using the apply rule it's broken:

Director Apply Rule preview:
```
apply Service "App - Automic Agent Broken Pipes" {
    import "REMOTE ES Query Automic Broken Pipe"

    assign where host.vars.app_automic && host.vars.app_automic_db

    import DirectorOverrideTemplate
}
```

Icinga 2 object:
```
# icinga2 object list --type Service --name "App - Automic Agent Broken Pipes"
Object 'REDACTED!App - Automic Agent Broken Pipes' of type 'Service':
  % declared in '/var/lib/icinga2/api/packages/director/4e72a767-6b75-4fff-b2d6-1b55f2066b4b/zones.d/master/service_apply.conf', lines 1:0-1:47
  /** truncated **/
  * zone = "satellite"
    % = modified in '/var/lib/icinga2/api/packages/director/4e72a767-6b75-4fff-b2d6-1b55f2066b4b/zones.d/master/service_apply.conf', lines 1:0-1:47
```

The line where the zone is modified just contains the apply rule I pasted above.

### When assigning directly to a host it works:

Director Service preview:
```
object Service "App - Automic Agent Broken Pipes" {
    host_name = "REDACTED"
    import "REMOTE ES Query Automic Broken Pipe"

}
```

Icinga 2 object:
```
# icinga2 object list --type Service --name "App - Automic Agent Broken Pipes"
Object 'REDACTED!App - Automic Agent Broken Pipes' of type 'Service':
 % declared in '/var/lib/icinga2/api/packages/director/18db1d66-a3ae-4099-8526-ae7c6cbfc4ac/zones.d/master/services.conf', lines 57:1-57:49
  /** truncated **/
  * zone = "master"
```

## Steps to Reproduce (for bugs)
- Create a service template with `Run on Agent = false` and `Zone = master`
- Apply it through Director using an apply rule to a host in another zone -> it will stay pending: Broken
- Apply it through Director directly to a host -> it works
- Apply it using an apply rule in /etc/icinga2/zones.d/master -> it works

## Your Environment

* Director version (System - About): 1.5.1
* Icinga Web 2 version and modules (System - About): 2.6.1
* Icinga 2 version (`icinga2 --version`): r2.9.1-1
* Operating System and version: Debian 9.5
* Webserver, PHP versions:

**Comment by Thomas-Gelf** [comment] 2018-09-04 10:39
Thanks @matthenning. It took some time, but now I believe to fully understand your problem. As Icinga 2 does not respect the Zone from `zones.d/<zone>/whatever.conf` (and I guess there is no quick way to change this), I'll prepare a pull request for the Director enforcing the following behavior:

* WHEN a Service is an Apply Rule
* AND the calculated Rendering Zone is NOT a global zone
* THEN render `zone = "<zone>"` for that Apply Rule

Even if placing the config into `zones.d/<zone>` might suggest that this should already be the case.

**Comment by matthenning** [comment] 2018-09-04 11:04
Sorry for that, I was struggling to explain it as I just barely understood what was going on myself :)
Thank you for the quick reply, let me know if you need more information.

**Comment by Marci24h** [comment] 2018-09-17 10:54
Got the same Probleme.
Our Enviroment has the same Version levels. (Icinga2, Icingaweb2, director)
We are not able to test the linked commit because, we habe Apply Rules in other Zones.

**Comment by Thomas-Gelf** [comment] 2018-09-17 10:59
@Marci24h, @matthenning : it would really help if one of you could try the linked pull request and let us know whether it works as expected.

**Comment by matthenning** [comment] 2018-09-17 12:00
@Thomas-Gelf it's on my todo list, but I just didn't come around to it yet.
I'm hopefully getting it done early this week.

**Comment by Marci24h** [comment] 2018-09-17 15:56
@Thomas-Gelf
i'll update a smaller installation to the same Versions und try it there.

**Comment by Marci24h** [comment] 2018-09-18 12:57
@matthenning
i updated a smaller environment and added a Satellite.
Afterwards i created a Testing Host named "gateway"
The Service "ping-custom_attached2host" was directly added to the Host in director via Services Tab.
The Service "ping-custom_via-apply-rules" has been created as apply Rule importing an Service Template within the Master Zone.
The Error was reproducable.
The Service ping-custom_attached2host has been checked by the master
The Service ping-custom_via-apply-rules hasn't been executed.

After checking out the commit c560a87 und redepolying Service ping-custom_via-apply-rules has been checked.
In this Enviroment no apply Rules exists in other Zones.

befor:
```
root@master:~# icinga2 object list --type Service --name 'gateway*'
 Object 'gateway!ping-custom_attached2host' of type 'Service':
     * zone = "master.domain.tld"
 Object 'gateway!ping4' of type 'Service':
    * zone = "satellite"
    % = modified in '/etc/icinga2/conf.d/services.conf', lines 26:1-26:21
 Object 'gateway!ping-custom_via-apply-rules' of type 'Service':
    * zone = "satellite" <--- wrong
    % = modified in '/var/lib/icinga2/api/packages/director/62fe7d17-80f0-4d2b-b3f5-bec90a702367/zones.d/master.domain.tld/service_apply.conf', lines 1:0-1:42
```

After commit c560a87:
```
root@master:~# icinga2 object list --type Service --name 'gateway*'
 Object 'gateway!ping-custom_attached2host' of type 'Service':
   * zone = "master.domain.tld"
 Object 'gateway!ping4' of type 'Service':
    * zone = "satellite"
    % = modified in '/etc/icinga2/conf.d/services.conf', lines 26:1-26:21
 Object 'gateway!ping-custom_via-apply-rules' of type 'Service':
    * zone = "master.domain.tld" <--- correct
    % = modified in '/var/lib/icinga2/api/packages/director/d2f9635d-ad1f-4bcb-8c79-65ffbb385518/zones.d/master.domain.tld/service_apply.conf', lines 1:0-1:42
    % = modified in '/var/lib/icinga2/api/packages/director/d2f9635d-ad1f-4bcb-8c79-65ffbb385518/zones.d/master.domain.tld/service_apply.conf', lines 5:5-5:36
```
_The Output was truncated._

**Director Objects Preview:**
```
zones.d/director-global/host_templates.conf
template Host "ping-host" {
    check_command = "hostalive_custom"
    max_check_attempts = "3"
    check_interval = 3m
    retry_interval = 29s
    check_timeout = 7s
    enable_active_checks = true
    enable_passive_checks = true
    enable_perfdata = true
}

zones.d/satellite/hosts.conf
object Host "gateway" {
    import "ping-host"

    display_name = "gateway"
    address = "10.10.0.100"
}

zones.d/master.domain.tld/services.conf
object Service "ping-custom_attached2host" {
    host_name = "gateway"
    import "ping-custom"

}

zones.d/master.domain.tld/service_apply.conf
apply Service "ping-custom_via-apply-rules" {
    import "ping-custom"

    assign where host.name == "gateway"
    zone = "master.domain.tld"

    import DirectorOverrideTemplate
}
```

**Comment by Thomas-Gelf** [comment] 2018-10-30 16:43
@lazyfrosch: thoughts? v1.6.0 is soon, and I'd prefer not to merge this the very last day.

**Comment by lazyfrosch** [comment] 2018-10-31 08:02
In theory this is a nice idea to "move" checks from a sub-zone to a parent zone.

Which will work, but there are lots of settings that won't work in this case.

I'm only worried that people won't understand how this works. And I just wished we had more documentation on this, especially in Director.

I had a user last week, that misused this field in the believe it would move checks to a certain zone (in addition to setting it on the host). The upgrade to 1.5 resulted in him having wrong configuration.

If a user has not configured this correctly we will only notice this in two ways:
* Checks are missing or not applied
* Checks are not executed (overdue dashboard)

**Comment by Thomas-Gelf** [comment] 2018-10-31 08:58
Could you please check whether this patch have helped him? Can you build a small sample configuration that would work correctly right now, but break with this change?

**Comment by Thomas-Gelf** [comment] 2018-12-09 16:13
Not enough testing, moving to next version

**Comment by swizzly** [comment] 2019-03-08 12:23
(self-ping by @Thomas-Gelf)

**Closed** 2019-09-25 12:37 UTC
Labels: bug
