### ISSUE TITLE
import source add "director." to tablename, second try

### ISSUE THREAD

**Issue by magheinz** [Icinga/icingaweb2-module-director#1174] opened 2017-09-12 08:16 UTC
Error when modifing SQL-Statment for import-source
`Error: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'director.glpi_computers' doesn't exist, query was: foobar`
The table is glpi_computers in database glpi. Before update (git pull) it works, now its not working anymore
If change the SQL-statement from `from glpi_computers` to `from glpi.glpi_computers` the error
`SQLSTATE[42000]: Syntax error or access violation: 1142 SELECT command denied to user 'director'@'localhost' for table`
director is not the configured user!

    Director version (System - About): master
    Icinga Web 2 version and modules (System - About): 2.4.1
    Icinga 2 version (icinga2 --version): r2.7.0-1
    Operating System and version: debian stretch
    Webserver, PHP versions:apache 2.4.25-3+deb9u2, php 5.6.30+dfsg-0+deb8u1

**Comment by Thomas-Gelf** [comment] 2017-09-12 08:19
@magheinz: what's the exact GIT hash of your installed version? To me this looks like a duplicate of #1173 - this should have been fixed this night.

**Comment by magheinz** [comment] 2017-09-12 08:24
ups, my fault. i thougt "sorry, my fault - please try again!" means the ticket, not the bug,
After some test i think the problem is resolved this night.
thank you very mutch!

**Comment by Thomas-Gelf** [comment] 2017-09-12 08:25
You're welcome!

**Closed by Thomas-Gelf** 2017-09-12 08:25 UTC
