### ISSUE TITLE
removing host(s) with a result of an empty zone doesn't remove hosts from icinga config

### ISSUE THREAD

**Issue by tlo8640** [Icinga/icingaweb2-module-director#1219] opened 2017-10-09 15:57 UTC
Hello,

when trying to remove hosts froom icinga using the director, with the result that a check zone is empty after removing the hosts, then the config sync doesn't removes the hosts from icinga config.

## Expected Behavior

removing hosts should remove hosts everytime, also if a configured zone has no configured hosts anymore (think about migration of hosts from one checkzoen to another)

## Current Behavior

If you remove one or more hosts from config with the result, that the configured checkzone is empty after removing the hosts, then the hosts in the checkzone will be removed from the director config, but they still exist in the icinga config after config deploy.

## Possible Solution

It seems to me, that because for the empty zone exists no hosts.conf anymore (for the director deploy), no "new" hosts.conf will be deployed, but the existing(old) hosts.conf (in the icinga2 config) for this zone will not removed, so the hosts still exist in icinga2. 
Perhaps something like rsync without "--delete"? ;-)

## Steps to Reproduce (for bugs)
1. setup icinga2 with director
2. create one or more zones
3. deploy one or more hosts into the zone(s), only hostchecks are ok
4. remove all hosts from one zone so that the zone should be empty 
5. deploy new config with director
6. voila: the removed hosts still exist in icinga2, but are removed from director

## Context
Currently we try to set new icinga2 environment, with testing automatic registering in icinga2 using director API. So, only one or two (mostly less then 10 Hosts) are configured in director. When we tried to remove them, We were surprised, the the director config is empty, but in icinga the  hosts are still visible. The we found, that this only happens, when a zone is empty after removing the hosts.

## Our Environment
* Director version (System - About): master (two weeks ago)
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): v2.6.3
* Operating System and version: Red Hat Enterprise Linux Server release 7.4 (Maipo)
* Webserver, PHP versions: Apache 2.4.6, php 5.4.16

**Comment by Thomas-Gelf** [comment] 2017-10-10 11:55
This sounds like an issue in Icinga itself, could you please open a dedicated issue in the [Icinga 2 queue](https://github.com/Icinga/icinga2/issues)? Icinga 2 bug [#3323](https://github.com/Icinga/icinga2/issues/3323) might be related and should be addressed with [#4354](https://github.com/Icinga/icinga2/issues/4354). However, what you're describing sounds slightly different.

**Comment by tlo8640** [comment] 2017-11-03 14:01
created issue in icinga2:
https://github.com/Icinga/icingaweb2/issues/3059

**Comment by tlo8640** [comment] 2017-11-07 08:39
There was an error in creating a ticket in icinga2. I accidentally created it in icingaweb2 (what is definitely wrong), and should removed.
Now I created it in the (in my opinion right place) icinga2:
https://github.com/Icinga/icinga2/issues/5722

Thanks for taking care 
Thomas

**Comment by Thomas-Gelf** [comment] 2018-05-04 10:34
The linked issue has been closed as being a duplicate, and the root cause seems to be pretty dated. Therefore I made an attempt to prioritize this on our internal tracker. Closing this issue, as the Director cannot help here.

**Closed by Thomas-Gelf** 2018-05-04 10:34 UTC
