### ISSUE TITLE
Notification apply scheme not removed when removing host from hostgroup

### ISSUE THREAD

**Issue by quentinsch** [Icinga/icingaweb2-module-director#1539] opened 2018-06-20 13:30 UTC
## Expected Behavior
If you remove a host group from a host the apply rules should gone as well from the host.

## Current Behavior
If you have deployed an apply rule with a notification scheme it is nicely applied. When you remove the host group from a host, the applied group is not removed and is still active.

## Possible Solution
Not sure, probably recalculation of the apply rules.

## Steps to Reproduce (for bugs)
-  Create a host group
- Add a host to host group
- Create a notification apply rule (apply where host.groups = hostgroupname)
- You see the notifiers appear when viewing the details of a host
- Remove the host from the host group
- Deploy config within the director
- View the details of the host again, you still see the notifiers active.

## Your Environment
* Director version:  v1.4.3
* Icinga Web 2 version and modules: v2.5.3
* Icinga 2 version: r2.8.4-1
* Operating System and version: Debian 8.10
* Webserver, PHP versions:
Apache 2.4.10-10+deb8u12
PHP 7.1.18-1+0~20180611145758.18+jessie~1.gbp2b32f6
MySQL 5.5.60-0+deb8u1

**Comment by Thomas-Gelf** [comment] 2018-06-20 13:34
Related bugs have been fixed in the current master, fixes will be part of v1.5.0. It would be great if you could try whether you're able to reproduce this with the latest master. Tests are red since yesterday, but that's an error in the tests, not in the code - will be fixed :laughing: 

What I'm unable to understand: where do you see a related notification when showing your Host? That would be a nice feature, but right now it shouldn't be there at all.

**Comment by quentinsch** [comment] 2018-06-20 13:41
Ok, glad this issue was noticed before and there is a fix for it! ;)
I'll try the latest master to see if it works in my case.
Well, if there is no notification scheme applied it is empty in the host details like this:
![screen shot 2018-06-20 at 15 37 29](https://user-images.githubusercontent.com/7438854/41661955-39cbc504-74a0-11e8-9a4d-19a59f0a8893.png)
And if there is a notification rule applied, then it looks like this:
![screen shot 2018-06-20 at 15 37 44](https://user-images.githubusercontent.com/7438854/41661982-4b4b6de8-74a0-11e8-8b07-bebee74a8e92.png)
The problem is that it stays there when the condition for the apply rule has changed or removed. But as mentioned, I'll try the latest master.

**Comment by Thomas-Gelf** [comment] 2018-06-20 13:44
There shouldn't have been changes affecting the deployed configuration, just some preview parts inside the Director have changed. They affected the permission/restriction system, but not what you're showing. Could you please let me have a more concrete example with real/anonymized data to get a better understanding of what's going on?

**Comment by quentinsch** [comment] 2018-06-20 14:11
Allright, when trying to make the steps for reproduction I found the issue, but I am still a bit confused why... :(
It seems that my apply rules were wrong. What I had (and this why it applies in certain conditions):

![screen shot 2018-06-20 at 16 05 07](https://user-images.githubusercontent.com/7438854/41663604-1c41172e-74a4-11e8-9c7e-69915458a9c0.png)

What I wanted to achieve that either the host belongs to a host group name or is not member of host group Silent then apply the rule.
The simple way is to do it like this:

![screen shot 2018-06-20 at 16 04 13](https://user-images.githubusercontent.com/7438854/41663720-6189010c-74a4-11e8-8eaf-68670d23efd3.png)

So I am a bit confused with the nested AND/OR statements... Maybe this can be a bit improved in future versions to get it more clear?

Conclusion is that the apply rules work as expected, so this issue can be closed regarding the initial issue.

**Comment by Thomas-Gelf** [comment] 2018-06-20 14:58
The != in combination with host.groups could be the problem, could you please show me your config preview? Eventual workaround -> add a NOT to the mix, and create NOT -> host.groups = Silent. But anyways, your example should work - so please show me the rendered configuration!

**Comment by quentinsch** [comment] 2018-06-20 15:02
Sure, the rendered config is:

`apply Notification "slack-notify-host-bi" to Host {
    import "slack-notifications-default-configuration-hosts"

    period = "24x7"
    assign where host.vars.slack_notifications == "enabled" && host.vars.not_per == "24x7" && "BI-Slack" in host.groups && !("Silent" in host.groups)
    states = [ Down, Up ]
    types = [
        Acknowledgement,
        Custom,
        DowntimeEnd,
        DowntimeRemoved,
        DowntimeStart,
        FlappingEnd,
        FlappingStart,
        Problem,
        Recovery
    ]
    user_groups = [ "slack" ]
    vars.slack_notifications_channel = "#slack-channel"
}`

**Comment by Thomas-Gelf** [comment] 2018-06-20 15:03
That's correct and should (once deployed) work as expected

**Comment by quentinsch** [comment] 2018-06-20 15:05
Yes it does now! Thanks anyway for your help!

**Comment by Thomas-Gelf** [comment] 2018-06-20 15:06
Wait... did you change anything?

**Comment by quentinsch** [comment] 2018-06-20 15:07
Nope

**Comment by Thomas-Gelf** [comment] 2018-06-20 15:08
So... false alarm? Just want to be sure that we don't miss anything :)

**Comment by quentinsch** [comment] 2018-06-20 15:10
Well the thing I changed that I removed the OR between the host.groups. After that it worked as expected.

**Comment by Thomas-Gelf** [comment] 2018-06-20 15:12
So, in case you think this was a logical error at your side we can close this :laughing:
Otherwise please show me filter & preview of your former configuration

**Comment by quentinsch** [comment] 2018-06-20 15:15
Well this is the old one:
apply Notification "slack-notify-host-bi" to Host {
    import "slack-notifications-default-configuration-hosts"

    period = "24x7"
    assign where host.vars.slack_notifications == "enabled" && host.vars.not_per == "24x7" && ("BI-Slack" in host.groups || !("Silent" in host.groups))
    states = [ Down, Up ]
    types = [
        Acknowledgement,
        Custom,
        DowntimeEnd,
        DowntimeRemoved,
        DowntimeStart,
        FlappingEnd,
        FlappingStart,
        Problem,
        Recovery
    ]
    user_groups = [ "slack" ]
    vars.slack_notifications_channel = "#slack-channel"
}

In my opinion they should do the same, but maybe I am confused...

**Comment by Thomas-Gelf** [comment] 2018-06-20 15:19
PEBCAK :stuck_out_tongue_closed_eyes: 

`car AND NOT tesla` is not the same as `car OR NOT tesla`, because the second one is still true for any tesla.

**Comment by Thomas-Gelf** [comment] 2018-06-20 15:19
Guess we can close this

**Closed by Thomas-Gelf** 2018-06-20 15:19 UTC
