### ISSUE TITLE
Deployments fail after updating Director to 1.5.1

### ISSUE THREAD

**Issue by rojobull** [Icinga/icingaweb2-module-director#1616] opened 2018-08-23 12:35 UTC
## Expected Behavior
Deployments succeed

## Current Behavior
There is a line that appeared in one of my service templates that is causing deployments to fail with this error:
`[2018-08-21 14:29:56 -0500] critical/config: Error: object rule 'ignore where' cannot be used without 'assign where`
When I look at the preview for the service template this line appeared:
`ignore where host.name == host_fqdn`
When I click on show resolved, it disappears. If I clone the service template the “ignore where” line does not appear in the new service template. Note, the host is an actual host being monitored.

## Possible Solution
Manually remove this "ignore where" line in the Director database? I am not sure how to do this. I also could not figure out how to do this using the Icinga Director CLI or the Director API. I could be doing something wrong but the CLI/API seem to only update the "resolved" object but not the actual service template which includes the line and breaks the deployments.

## Steps to Reproduce (for bugs)
Not sure how to reproduce. I suspect this happened because I was trying to blacklist a service for this same host. Blacklisting the service resulted in this ignore line being added to the service template. But now after upgrading Director I am not able to remove it. It is discussed in this closed issue. https://github.com/Icinga/icingaweb2-module-director/issues/1519#event-1784719136

## Your Environment
* Director version 1.5.1
* Icinga Web 2 version and modules: 2.5.3
* Icinga 2 version: 2.9.1-1
* Operating System and version: CentOS 7.4.1708
* Webserver, PHP versions: 5.4.16-43.el7_4

**Comment by rojobull** [comment] 2018-08-23 17:51
I ended up creating a new service template and changing all of the services to use that new template and the finally deleting the bad service template. Once I did this, deployments started working again.

I still think this is a bug that could re-occur at some point. Somehow, blacklisting a service caused this change in the service template which was then impossible to remove.

**Comment by lazyfrosch** [comment] 2018-08-24 09:30
This seems to be caused by the new blacklisting logic, where a blacklist is set, while no assign is specified.

Can you share some config examples and how you set blacklist?

**Comment by rojobull** [comment] 2018-08-24 12:30
I don't have any services blacklisted at the moment for fear of this issue re-occurring. I will create a new service and do some testing. Here's a description of what I had in place before when this issue occurred.
Prior to upgrade I was running Director 1.4.
I created service sets with multiple services and assign where rules using host.name to assign the service set. This work perfectly fine. For one host, that did not have one of the services running, I decided to blacklist a service instead of removing the host from the service set. So in Director I browsed to this host, browsed to the applied services and then selected the service set service and blacklisted it. This did not seem to work properly as was noted in https://github.com/Icinga/icingaweb2-module-director/issues/1519#event-1784719136. 
At this time, deployments were still working. As a result of the above mentioned issue, a new version was released. It was after updating to Director 1.5.1 that the deployments started failing. That's when I noticed the "ignore where" line had been added to the service template and was causing deployments to fail.

**Comment by Thomas-Gelf** [comment] 2018-08-24 13:01
@rojobull: there was no blacklisting in 1.4.x, and the bug you describe should have been fixed before 1.5.0. So I assume you have probably been running a master version somewhere in between, but that's fine.

There used to be a bug that took place when blacklisting a service from a set, it resulted in a blacklist entry for the template instead of for the service.

You can find the entries in question with:
```sql
SELECT s.id, bl.host_id, s.object_name
  FROM icinga_host_service_blacklist bl
  JOIN icinga_service s ON s.id = bl.service_id AND s.object_type = 'template';
```

If there are any matches, you can delete them with:
```sql
DELETE bl.*
  FROM icinga_host_service_blacklist bl
  JOIN icinga_service s ON s.id = bl.service_id AND s.object_type = 'template';
```

In case I'm wrong with my assumptions please let me know, because if there are still related bugs I'd love to see them fixed. One issue I could imagine would be an applied Service Set, blacklisted on a matching host - and removing the apply condition afterwards. I didn't test it, but that might be a scenario that could fit your example.

Thanks,
Thomas

**Comment by rojobull** [comment] 2018-08-24 13:05
Hi @Thomas-Gelf you are correct, I was running the master version. Going forward I will stick with only versions. Thank you for this info. I will do some testing later today and post my findings.

**Comment by Thomas-Gelf** [comment] 2018-08-24 13:15
That would explain it. Anyways, there is nothing wrong with running the master, we try hard to not breaking it at all. Obviously, release versions are tested more intensively.

**Comment by rojobull** [comment] 2018-08-24 16:16
Here's what I tested and what I observed.

I created a test service set with two services running the hostalive check command. I assigned the service set to a couple of nodes and deployed the changes. As expected, the services were properly added to the nodes.

Next, I blacklisted one of the services from the service set on one of the nodes. When I did this, it did strike it out in the services list but it did not show up in the activity log or show up as a pending change. I deployed anyways and then I confirmed that the service was properly removed from the node. I checked the service template and I did NOT see the "ignore where" line so that's good. I also tested removing the blacklist. That also does not show up in the activity log or a pending change but when I deploy anyways it works and the service is re-applied.

Next, as requested above, I removed the host from assign where in the service set. When I did this, while leaving the blacklist in place, it deployed correctly. The remaining service check which was not blacklisted was removed as expected. When I check the services for the node in Director, the service set services are gone, as expected.

So this seems to work properly now. The only thing that would be good to have is for blacklist changes to show up in the activity log and as a pending change to be deployed.

With regards to this specific issue, I suppose it is not an actual issue but rather something that was carried over from a prior version of Director. So we can likely close this.

**Comment by Thomas-Gelf** [comment] 2018-09-05 23:04
Easiest way to reproduce a similar error: add a Service Set to a Single Host, blacklist one of it's services.

**Comment by Thomas-Gelf** [comment] 2018-10-30 15:31
@mzhaase: sure. I'll move this to 1.6.0, as we'll probably release that version earlier than expected. This will allow us to tag v1.5.2.

**Comment by mzhaase** [comment] 2018-10-30 16:16
Thanks!On Oct 30, 2018 16:36, Thomas Gelf <notifications@github.com> wrote:@mzhaase: sure. I'll move this to 1.6.0, as we'll probably release that version earlier than expected. This will allow us to tag v1.5.2.

**Comment by Thomas-Gelf** [comment] 2018-10-30 16:37
@mzhaase: [v1.5.2](https://github.com/Icinga/icingaweb2-module-director/releases/tag/v1.5.2) is there, sorry for the delay.

**Comment by rafiwui** [comment] 2019-01-23 16:45
I am having the same issue (also running with master branch).
Will this be fixed on the master branch or do I need to checkout  v1.6.0 to have this fixed?

**Comment by terra-nova** [comment] 2019-02-11 10:04
Same issue here with director 1.6.0.

This bug makes the whole serviceset feature more or less unusable for us. We have many environments where 95% of the hosts have a certain set of services, but 5% are "different": Solaris VMs, the odd appliance that won't allow Vmware tools to be installed, etc. etc.

**Closed** 2019-02-14 23:51 UTC
Labels: area/apply-assign, bug
