### ISSUE TITLE
Windows Kickstart Script - Array for $GlobalZones is empty

### ISSUE THREAD

**Issue by ryanrudak** [Icinga/icingaweb2-module-director#2002] opened 2019-10-30 14:01 UTC
## Expected Behavior
Windows Kickstart Script:
    [array]$GlobalZones                 = @( 'director-global' ),

## Current Behavior
Windows Kickstart Script:
    [array]$GlobalZones                 = @(),

## Possible Solution
Change of the 'Windows Kickstart Script' back to:
    [array]$GlobalZones                 = @( 'director-global' ),

## Steps to Reproduce (for bugs)
Download the 'Windows Kickstart Script' from an existing hostobject.

The Linux commandline Script seems to be ok.
    ICINGA2_GLOBAL_ZONES=('director-global')

## Your Environment

* Director version (System - About): master (Git commit e871ba4d4ec0983aaa7e4f57c68fc213ccb103f4)
* Icinga Web 2 version and modules (System - About): 2.7.3
* Icinga 2 version (`icinga2 --version`): r2.10.5-1
* Operating System and version: debian 9.11
* Webserver, PHP versions: Apache/2.4.25 (Debian), PHP 7.0.33-0+deb9u5

**Comment by Thomas-Gelf** [comment] 2019-10-30 14:07
@LordHepipud: guess something has been changed here. Do I need to fill a new PS-Parameter?

**Comment by LordHepipud** [comment] 2019-10-30 22:17
This issue was introduced within the PowerShell module by allowing the overriding of arguments shipped by the Icinga Director. The default value for the global zones were not compiled properly, which causes this error.

The issue is already fixed on the current master of the PowerShell module with issue https://github.com/Icinga/icinga2-powershell-module/issues/93

We just need to ship the new version of the module with the director and everything will work as intended again.

I will open a request tomorrow.

Sorry for the trouble !

**Comment by Thomas-Gelf** [comment] 2019-10-31 08:08
Don't worry, thanks for the details!

**Comment by Thomas-Gelf** [comment] 2019-11-04 16:38
Thanks @LordHepipud!

**Closed by Thomas-Gelf** 2019-11-04 16:38 UTC
Labels: bug
