### ISSUE TITLE
Service wont show up when added via Apply Rule

### ISSUE THREAD

**Issue by Wintermute2k6** [Icinga/icingaweb2-module-director#1483] opened 2018-05-08 08:58 UTC
## Expected Behavior
When Service is attached via apply rule it should show up on the Services tab of the host/hosts

## Current Behavior
Doesn't show up when apply rule is set via "is true / or set" operator

## Possible Solution
No idea how to resolve this

## Steps to Reproduce (for bugs)
1) Cean Base Setup Icinga 2 & Icinga Web 2 + Director v1.4.3
2) Create Service & Host Template + Host and Service
3) Create Apply Rule for Service
4) Attach Service via apply rule with "is true / or set" operator. (Screen1)
![screen1](https://user-images.githubusercontent.com/7203835/39747815-a3a61420-52ae-11e8-8589-a87993c83a71.png)

5) Watch Host Services Tab where it doesn't show up (Screen2)
![screen2](https://user-images.githubusercontent.com/7203835/39747820-a6c6ecb0-52ae-11e8-8661-d7b9fa3f56b3.png)

## Your Environment

* Director version (System - About):
![director_version](https://user-images.githubusercontent.com/7203835/39747423-8988dd26-52ad-11e8-8f6d-7f64d1ec26c5.png)

* Icinga Web 2 version and modules (System - About):
![modules_version](https://user-images.githubusercontent.com/7203835/39747432-8eea01f0-52ad-11e8-9997-dafb7d32fc06.png)

* Icinga 2 version (`icinga2 --version`):
icinga2 - The Icinga 2 network monitoring daemon (version: r2.8.4-1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-693.21.1.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: unknown

* Operating System and version:
[root@test modules]# cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

* Webserver, PHP versions:

[root@test modules]# yum list installed | grep httpd
httpd.x86_64                     2.4.6-67.el7.centos.6    @updates              
httpd-tools.x86_64               2.4.6-67.el7.centos.6    @updates              
[root@test modules]# yum list installed | grep scl
centos-release-scl.noarch        2-2.el7.centos           @extras               
centos-release-scl-rh.noarch     2-2.el7.centos           @extras               
rh-php71-php-cli.x86_64          7.1.8-1.el7              @centos-sclo-rh       
rh-php71-php-common.x86_64       7.1.8-1.el7              @centos-sclo-rh       
rh-php71-php-fpm.x86_64          7.1.8-1.el7              @centos-sclo-rh       
rh-php71-php-gd.x86_64           7.1.8-1.el7              @centos-sclo-rh       
rh-php71-php-intl.x86_64         7.1.8-1.el7              @centos-sclo-rh       
rh-php71-php-json.x86_64         7.1.8-1.el7              @centos-sclo-rh       
rh-php71-php-ldap.x86_64         7.1.8-1.el7              @centos-sclo-rh       
rh-php71-php-mbstring.x86_64     7.1.8-1.el7              @centos-sclo-rh       
rh-php71-php-mysqlnd.x86_64      7.1.8-1.el7              @centos-sclo-rh       
rh-php71-php-pdo.x86_64          7.1.8-1.el7              @centos-sclo-rh       
rh-php71-php-pgsql.x86_64        7.1.8-1.el7              @centos-sclo-rh       
rh-php71-php-xml.x86_64          7.1.8-1.el7              @centos-sclo-rh       
rh-php71-php-zip.x86_64          7.1.8-1.el7              @centos-sclo-rh       
rh-php71-runtime.x86_64          1-1.el7                  @centos-sclo-rh       
scl-utils.x86_64                 20130529-18.el7_4        @updates              
sclo-php71-php-pecl-imagick.x86_64 3.4.3-2.el7              @centos-sclo-sclo

**Comment by pemontto** [comment] 2018-10-15 20:07
This is a duplicate of #1387 and #905 and has been bugging me for a bit. Though I find sometimes some apply rules do show up under services for a host, but sometimes they don't. I haven't yet been able to work out why.

**Comment by lazyfrosch** [comment] 2019-04-30 10:49
I currently do an evaluation on this... We need to implement our own Filter matcher for this to work properly...

**Closed** 2019-05-06 15:07 UTC
Labels: area/apply-assign, bug

**Comment by friesoft** [comment] 2019-05-06 16:12
Works great for us. I compared all services of a deployed host vs those shown in the host in director and the only differences were:
* sort order is crazy (I couldn't find an issue regarding this - will open one)
* apply for rules are rendered as single entries which may be technically correct because there is only one service apply rule but it is misleading imho and leads to errors like this: https://github.com/Icinga/icingaweb2-module-director/issues/831
* Services using manual config not shown => ok

So overall definitely an improvement, thanks! :smile:
