### ISSUE TITLE
duplicate services allowed to be created in ui

### ISSUE THREAD

**Issue by mbassett** [Icinga/icingaweb2-module-director#728] opened 2017-01-18 22:37 UTC
Possibly Mysql schema issue?   I am able to create 2 services with the same name accidentally using clone, and then the 2nd one is never able to be deleted through the UI as it always opens the 1st one (since it selects via name)  

Config pushes also predictably fail as you can't have 2 services with the same name.

**Comment by Thomas-Gelf** [comment] 2017-01-18 22:43
I'll close this as a duplicate of #364. This is tricky, as we usually delegate such duplicate detection to the database - but this i not possible with services. It is perfectly legal to have for example two apply rules with the very same name. This will be fixed, we just postponed it as it was trickier to fix than we thought.

As a workaround in the meantime please rename one of those services, then you should be able to delete it.

Cheers,
Thomas

**Closed by Thomas-Gelf** 2017-01-18 22:43 UTC
