### ISSUE TITLE
Add field Type "dictionary" and allow "apply for" to iterate over it's elements

### ISSUE THREAD

**Issue by widhalmt** [Icinga/icingaweb2-module-director#773] opened 2017-02-07 22:03 UTC
This should allow to recreate the examples from the Icinga 2 example config in `/etc/icinga2/conf.d`. Especially the vhosts and disks examples.

**Comment by vita2** [comment] 2017-02-07 22:37
+1

**Comment by jfrisvold** [comment] 2017-03-31 21:13
Yes please.  And this explains why I can't find an example of how to do this in the docs.  It doesn't look like there's currently a way.  We can reproduce the same effect by creating lots of hosts, but that just clutters up the interface.

**Comment by Thomas-Gelf** [comment] 2017-04-01 11:03
Sorry, I don't get it. Just because some example shows a hack of how to generate single services from attributes hardcoded to a Dictionary on the host this doesn't mean that this is now the only way of creating services. You can easily create single vhosts and disk services by just ... adding them to the host?

I'll close this issue, as there should already exist a related feature request asking for Dictionary support. We'll implement it sooner or later, but creating single services that way is and remains hackish, at least IMHO.

**Closed by Thomas-Gelf** 2017-04-01 11:03 UTC

**Comment by jfrisvold** [comment] 2017-04-03 12:27
You're absolutely right, I can enter each service in by hand.  It takes longer to do, but it's possible.  I am, however, surprised to hear that using dictionaries to create single services is a hack.  Especially since this is how the official icinga2 examples do it.  Perhaps I'm misunderstanding something?
