### ISSUE TITLE
clone hostgroup modify Anzeigename

### ISSUE THREAD

**Issue by tomabg** [Icinga/icingaweb2-module-director#817] opened 2017-02-27 07:50 UTC
Hi,

after cloning a hostgroup it is not possible to modify the Anzeigename without setting an apply rule.
Creatings new hostgroup is possible without apply rule.
I use director 1.3.1.

BR
Thomas

**Comment by Thomas-Gelf** [comment] 2017-02-27 18:00
@tomabg: sorry, I cannot follow you. I can perfectly clone a hostgroup and change it's "Anzeigename" afterwards.

**Comment by tomabg** [comment] 2017-02-27 18:09
Hi Tom,

it is only possible if you assign the Hostgroup to something in my case...it says value is required and Speichern has no effect.

**Comment by Thomas-Gelf** [comment] 2017-02-27 18:10
Could you please show me a related screenshot? I'm unable to reproduce this

**Comment by tomabg** [comment] 2017-02-27 18:22
attached the screenshot

**Comment by Thomas-Gelf** [comment] 2017-02-27 18:33
Now I got it. I'll close this in favor of #814 - describing the same issue. I'll immediately push a fix for this.

**Closed by Thomas-Gelf** 2017-02-27 18:33 UTC
